export const RANDOM_GENRES = [
  "Cyberpunk Polka", "Synthwave Bluegrass", "Death Metal Mariachi", "Lo-Fi Hip Hop Opera",
  "Trap Gregorian Chant", "Disco Doom Metal", "K-Pop Sea Shanty", "Jazz Drill",
  "Reggaeton Country", "Ska Classical", "Vaporwave Grunge", "Electro-Swing Grindcore",
  "Celtic Dubstep", "Flamenco Shoegaze", "Gospel Industrial", "Math Rock Lullaby",
  "Pirate Metal", "Space Disco", "Chiptune R&B", "Bossa Nova Hardstyle",
  "Acoustic Breakcore", "Symphonic Beatbox", "Psychedelic Barbershop", "Funk Punk",
  "Ambient Thrash", "Glitch Hop Salsa", "Neo-Soul Polka", "Industrial Reggae",
  "Bluegrass Techno", "Doom Jazz", "Kawaii Metal", "Mongolian Throat Singing EDM",
  "Gregorian Trap", "Baroque Pop Punk", "Surf Rock Opera"
];

export const RANDOM_TOPICS = [
  "a toaster that wants to be a refrigerator", "paying taxes in space",
  "a dog who learned to trade crypto", "dropping your ice cream on the sidewalk",
  "a time-traveling pigeon", "falling in love with a WiFi router",
  "the existential dread of a roomba", "a vampire who is allergic to the dark",
  "getting abducted by polite aliens", "a wizard stuck in traffic",
  "a ghost who is afraid of humans", "a superhero whose only power is making perfect toast",
  "a pirate who gets seasick", "a dragon hoarding coupons instead of gold",
  "a robot learning how to cry", "a sentient slice of pizza running from delivery guys",
  "a cat plotting world domination from a cardboard box", "a medieval knight trying to use a smartphone",
  "a zombie who just wants a hug", "a secret agent whose cover is a clown"
];

export const RANDOM_VOCALS = [
  "male vocalist", "female vocalist", "androgynous vocals", "vocal group", "choir", "a cappella", "duet", "screamo"
];

export const RANDOM_MOODS = [
  "energetic", "dark", "playful", "melancholic", "romantic", "aggressive", "bittersweet", "introspective", "uplifting", "hypnotic", "calm", "angry", "mysterious", "epic", "ominous", "happy", "sad", "peaceful", "sarcastic", "sensual"
];

// Unified artist list — every key here MUST exist in the backend ARTIST_MAP
export const ARTISTS = [
  // Core working artists (original set)
  { key: "Snoopys Log", label: "Snoopys Log 🌲", real: "Snoop Dogg", gender: "MALE", style: "LAID-BACK, NASAL, SLURRED WEST COAST DRAWL. RHYTHMIC FLOW." },
  { key: "The Pelvis", label: "The Pelvis 🕺", real: "Elvis Presley", gender: "MALE", style: "Rich baritone, rockabilly vibrato, king energy." },
  { key: "Kitten Berry", label: "Kitten Berry 🐱", real: "Katy Perry", gender: "FEMALE", style: "Nasally pop tone, bright, breathy verses, powerful belting chorus, playful delivery." },
  { key: "Taylor Swiftly", label: "Taylor Swiftly 🏃‍♀️", real: "Taylor Swift", gender: "FEMALE", style: "Twangy nasal delivery, clear country enunciation, storytelling cadence, melodic hooks." },
  { key: "Billie Eyelash", label: "Billie Eyelash 👁️", real: "Billie Eilish", gender: "FEMALE", style: "Haunting, whispery vocals, bass-heavy production." },
  { key: "Eminem&M", label: "Eminem&M 🍬", real: "Eminem", gender: "MALE", style: "Fast-paced, aggressive, staccato rapping." },
  { key: "Freddie Thermometer", label: "Freddie Thermometer 🌡️", real: "Queen", gender: "MALE", style: "Freddie Mercury: thunderous tenor, 4-octave range, operatic vibrato, SHOWMAN delivery, audience call-response." },
  { key: "Daft Punk'd", label: "Daft Punk'd 🤖", real: "Daft Punk", gender: "MALE", style: "Robotic vocals, French house, electronic." },
  { key: "Derek Makson", label: "Derek Makson 🧤", real: "Michael Jackson", gender: "MALE", style: "Smooth, melodic, incredible runs and falsetto." },
  { key: "Metallica Mittens", label: "Metallica Mittens 🤘", real: "Metallica", gender: "MALE", style: "Heavy metal, distorted guitars, powerful vocals." },
  { key: "DJ Cottage Cheese", label: "DJ Cottage Cheese 🧀", real: "Skrillex", gender: "MALE", style: "Dubstep, heavy bass, electronic production." },
  { key: "Country Bot 3000", label: "Country Bot 3000 🤠", real: "Johnny Cash", gender: "MALE", style: "Deep authoritative baritone, country twang, dead-eye serious storytelling, man in black growl." },
  { key: "Jazz Hands Jeff", label: "Jazz Hands Jeff 🎷", real: "Miles Davis", gender: "MALE", style: "Jazz trumpet, smooth improvisation." },
  { key: "Opera Ooze", label: "Opera Ooze 🐌", real: "Luciano Pavarotti", gender: "MALE", style: "Powerful operatic tenor, dramatic vibrato." },
  { key: "Parody Prince", label: "Parody Prince 💜", real: "Prince", gender: "MALE", style: "Falsetto, funk rock, sexual energy." },
  { key: "Mocking Madonna", label: "Mocking Madonna 💃", real: "Madonna", gender: "FEMALE", style: "Breathy modal voice, seductive whisper verses, powerful belted chorus, dance-pop inflection." },
  { key: "Satire Sheeran", label: "Satire Sheeran 🎸", real: "Ed Sheeran", gender: "MALE", style: "Soft acoustic tone, breathy delivery, melodic vocal runs, loop pedal layers, warm intimate feel." },
  { key: "Giggle Gaga", label: "Giggle Gaga 🦄", real: "Lady Gaga", gender: "FEMALE", style: "Powerful belter, theatrical, dance-pop." },
  { key: "Post Malone Alone", label: "Post Malone Alone 🍺", real: "Post Malone", gender: "MALE", style: "Autotuned, melodic, slurred delivery." },
  { key: "The Weekend Warrior", label: "The Weekend Warrior 🌙", real: "The Weeknd", gender: "MALE", style: "R&B falsetto, dark atmosphere, smooth." },
  { key: "Dua Flippa", label: "Dua Flippa 💿", real: "Dua Lipa", gender: "FEMALE", style: "Breathy cool pop tone, rhythmic delivery, sassy attitude, disco-inflected groove." },
  { key: "Bruno Mars Bars", label: "Bruno Mars Bars 🍫", real: "Bruno Mars", gender: "MALE", style: "Powerful soulful tenor, stunning falsetto runs, retro pop energy, dynamic range." },
  { key: "Ariana Grandé-Latte", label: "Ariana Grandé-Latte ☕", real: "Ariana Grande", gender: "FEMALE", style: "Whistle notes, R&B-pop, incredible range." },
  { key: "Drake Snake", label: "Drake Snake 🐍", real: "Drake", gender: "MALE", style: "Toronto nasal flow, melodic hooky rapping, emotional R&B crossover, auto-tuned vulnerability." },
  { key: "Cardi B-hive", label: "Cardi B-hive 🐝", real: "Cardi B", gender: "FEMALE", style: "Dominant flow, Bronx energy, hip-hop." },
  { key: "Megan Thee Stal-lion", label: "Megan Thee Stal-lion 🦁", real: "Megan Thee Stallion", gender: "FEMALE", style: "Confident, Southern, hip-hop flow." },
  { key: "Nicki Mi-naj", label: "Nicki Mi-naj 👑", real: "Nicki Minaj", gender: "FEMALE", style: "Rapid flow, alter egos, hip-hop." },
  { key: "Travis Scott-ish", label: "Travis Scott-ish 🌵", real: "Travis Scott", gender: "MALE", style: "Auto-tuned, psychedelic, ad-libs." },
  { key: "21 Sav-age", label: "21 Sav-age 🔪", real: "21 Savage", gender: "MALE", style: "Trap, deep voice, melodic." },
  { key: "Snoop Dogg-y", label: "Snoop Dogg-y 🐕", real: "Snoop Dogg", gender: "MALE", style: "LAID-BACK, NASAL, SLURRED WEST COAST DRAWL." },
  { key: "Bob Mar-ley", label: "Bob Mar-ley 🌿", real: "Bob Marley", gender: "MALE", style: "Laid-back reggae rhythm, peaceful calm voice, spiritual positivity, rhythmic One Love delivery." },
  { key: "Kurt Cob-ain", label: "Kurt Cob-ain 💔", real: "Kurt Cobain", gender: "MALE", style: "Grunge, anguished vocals, raw." },
  { key: "David Bow-tie", label: "David Bow-tie 🎀", real: "David Bowie", gender: "MALE", style: "Otherworldly ethereal voice, dramatic flair, theatrical vibrato, chameleon timbre shifts." },
  { key: "The Beetles", label: "The Beetles 🪲", real: "The Beatles", gender: "MALE", style: "British invasion harmonies, melodic pop-rock, tight 4-part vocal arrangements, catchy hooks." },
  { key: "Elvis Pelvis", label: "Elvis Pelvis 🕺", real: "Elvis Presley", gender: "MALE", style: "Rich southern baritone, rockabilly growl, hip-swinging swing, gospel power." },
  { key: "Michael Jack-son", label: "Michael Jack-son 🧤", real: "Michael Jackson", gender: "MALE", style: "Smooth, incredible runs, pop perfection." },
  { key: "Ed Shearing", label: "Ed Shearing 🧶", real: "Ed Sheeran", gender: "MALE", style: "Acoustic pop, storytelling, warm vocals." },
  { key: "Kendrick Llama", label: "Kendrick Llama 🦙", real: "Kendrick Lamar", gender: "MALE", style: "Intelligent rap, socially conscious, poetic." },
  { key: "Justin Bee-ber", label: "Justin Bee-ber 🐝", real: "Justin Bieber", gender: "MALE", style: "Light youthful tenor, breathy pop tone, smooth melodic runs, gentle falsetto." },
  { key: "Selena Go-mez", label: "Selena Go-mez 🌙", real: "Selena Gomez", gender: "FEMALE", style: "Soft breathy pop tone, intimate delivery, clean melodic lines, gentle intimacy." },
  { key: "Shawn Men-des", label: "Shawn Men-des 🧵", real: "Shawn Mendes", gender: "MALE", style: "Pure clean tenor, acoustic intimacy, sincere earnest delivery, soft falsetto." },
  { key: "Camila Ca-bello", label: "Camila Ca-bello 🛎️", real: "Camila Cabello", gender: "FEMALE", style: "Latin-accented warmth, sensual whisper verses, powerful chest voice, Havana flow." },
  { key: "Harry Styles-ish", label: "Harry Styles-ish 🍉", real: "Harry Styles", gender: "MALE", style: "Retro pop rock, charismatic, falsetto." },
  { key: "Miley Cy-rus", label: "Miley Cy-rus 🚀", real: "Miley Cyrus", gender: "FEMALE", style: "Powerful belter, rock influences, edgy." },
  { key: "Demi Lo-vato", label: "Demi Lo-vato ❤️‍🩹", real: "Demi Lovato", gender: "FEMALE", style: "Powerful vocals, pop-rock, emotional." },
  { key: "Nick Jonas-brother", label: "Nick Jonas-brother 🎸", real: "Nick Jonas", gender:"MALE", style: "Pop vocals, falsetto, R&B influences." },
  { key: "Joe Jonas-brother", label: "Joe Jonas-brother 🎤", real: "Joe Jonas", gender: "MALE", style: "Pop vocals, catchy, youthful energy." },
  { key: "Kevin Jonas-brother", label: "Kevin Jonas-brother 🎹", real: "Kevin Jonas", gender: "MALE", style: "Pop vocals, harmonies, gentle." },
  { key: "Doja Cat-nip", label: "Doja Cat-nip 🐈", real: "Doja Cat", gender: "FEMALE", style: "Playful flow, R&B-pop, quirky." },
  { key: "Lil Nas X-ray", label: "Lil Nas X-ray 🩻", real: "Lil Nas X", gender: "MALE", style: "Country-rap fusion, nasal delivery, viral." },
  { key: "Jack Har-low", label: "Jack Har-low 🎩", real: "Jack Harlow", gender: "MALE", style: "Southern rap, smooth flow, confident." },
  { key: "DaBa-by", label: "DaBa-by 👶", real: "DaBaby", gender: "MALE", style: "Fast-paced rap, energetic, Charlotte flow." },
  { key: "Lil Ba-by", label: "Lil Ba-by 🍼", real: "Lil Baby", gender: "MALE", style: "Melodic rap, emotional, trap influence." },
  { key: "J. Cole-slaw", label: "J. Cole-slaw 🥗", real: "J. Cole", gender: "MALE", style: "Thoughtful rap, introspective, poetic." },
  { key: "Future-istic", label: "Future-istic 🔮", real: "Future", gender: "MALE", style: "Trap, auto-tuned, melancholic." },
  { key: "Young Thug-ger", label: "Young Thug-ger 🐍", real: "Young Thug", gender: "MALE", style: "Avant-garde rap, unique flow, melodic." },
  { key: "Playboi Car-ti", label: "Playboi Car-ti 🛒", real: "Playboi Carti", gender: "MALE", style: "Trap, auto-tuned, energetic ad-libs." },
  { key: "Lil Uzi Vert-ical", label: "Lil Uzi Vert-ical 📏", real: "Lil Uzi Vert", gender: "MALE", style: "Phonk-influenced, auto-tuned, hyper." },
  { key: "Migos-amigos", label: "Migos-amigos 🌮", real: "Migos", gender: "MALE", style: "Trap, triplet flow, ad-libs." },
  { key: "Rae Sremm-urd", label: "Rae Sremm-urd 🌀", real: "Rae Sremmurd", gender: "MALE", style: "Catchy trap, youthful, upbeat." },
  { key: "Swae Lee-way", label: "Swae Lee-way 🛣️", real: "Swae Lee", gender: "MALE", style: "Melodic rap, smooth, radio-friendly." },
  { key: "Slim Jxm-mi", label: "Slim Jxm-mi 🕶️", real: "Slim Jxmmi", gender: "MALE", style: "Aggressive flow, Rae Sremmurd duo." },
  { key: "Juice WRLD-wide", label: "Juice WRLD-wide 🧃", real: "Juice WRLD", gender: "MALE", style: "Emo rap, auto-tuned, emotional." },
  { key: "XXXTen-tacion", label: "XXXTen-tacion ❓", real: "XXXTentacion", gender: "MALE", style: "Emo rap, raw, aggressive." },
  { key: "Lil Peep-hole", label: "Lil Peep-hole 🐥", real: "Lil Peep", gender: "MALE", style: "Emo rap, melodic, underground." },
  { key: "Mac Mil-ler", label: "Mac Mil-ler 🍎", real: "Mac Miller", gender: "MALE", style: "Conscious rap, jazz-influenced, introspective." },
  { key: "Tyler The Cre-ator", label: "Tyler The Cre-ator 🌻", real: "Tyler, The Creator", gender: "MALE", style: "Odd rap, whimsical, experimental." },
  { key: "Frank Ocean-ic", label: "Frank Ocean-ic 🌊", real: "Frank Ocean", gender: "MALE", style: "R&B, emotional, falsetto." },
  { key: "A$AP Rock-y", label: "A$AP Rock-y 🗿", real: "A$AP Rocky", gender: "MALE", style: "Hustle rap, laid-back, fashion-forward." },
  { key: "Childish Gam-bino", label: "Childish Gam-bino 🍕", real: "Childish Gambino", gender: "MALE", style: "Intelligent rap, funk influences, theatrical." },
  { key: "Pharrell Wil-liams", label: "Pharrell Wil-liams 🎩", real: "Pharrell Williams", gender: "MALE", style: "Funk-pop, falsetto, producer." },
  { key: "Kanye West-ern", label: "Kanye West-ern 🤠", real: "Kanye West", gender: "MALE", style: "Auto-tuned rap, production-forward, ambitious." },
  { key: "Jay-Z-ebra", label: "Jay-Z-ebra 🦓", real: "Jay-Z", gender: "MALE", style: "Business rap, confident, lyrical." },
  { key: "Nas-ty", label: "Nas-ty 🗽", real: "Nas", gender: "MALE", style: "Lyrical rap, NY flow, storytelling." },
  { key: "Dr. Dre-idel", label: "Dr. Dre-idel 🕎", real: "Dr. Dre", gender: "MALE", style: "West Coast rap, smooth, producer." },
  { key: "Ice Cube-icle", label: "Ice Cube-icle 🧊", real: "Ice Cube", gender: "MALE", style: "Hardcore rap, aggressive, storytelling." },
  { key: "Eazy-E-rider", label: "Eazy-E-rider 🏍️", real: "Eazy-E", gender: "MALE", style: "Gangsta rap, raw, N.W.A." },
  { key: "50 Cent-ipede", label: "50 Cent-ipede 🐛", real: "50 Cent", gender: "MALE", style: "Hardcore rap, catchy hooks, trauma." },
  { key: "Rihanna-nana", label: "Rihanna-nana 🍌", real: "Rihanna", gender: "FEMALE", style: "Breathy seductive R&B tone, island inflection,Umbrella hook, anti-love song power." },
  { key: "Beyoncé-nce", label: "Beyoncé-nce 🐝", real: "Beyoncé", gender: "FEMALE", style: "Massive chest voice, stunning runs, gospel power, commanding queen presence, Destiny's Child harmonies." },
  { key: "Alicia Keys-board", label: "Alicia Keys-board ⌨️", real: "Alicia Keys", gender: "FEMALE", style: "Raw soulful piano voice, gospel power, Harlem church roots, commanding range." },
  { key: "John Leg-end", label: "John Leg-end 🦵", real: "John Legend", gender: "MALE", style: "Soulful pop, smooth falsetto, romantic." },
  { key: "Usher-er", label: "Usher-er 🎟️", real: "Usher", gender: "MALE", style: "Smooth R&B tenor, seduction falsetto, Yeah! Yeah! Yeah! energy, velvet smoothness." },
  { key: "Chris Brown-ie", label: "Chris Brown-ie 🍫", real: "Chris Brown", gender: "MALE", style: "Smooth R&B tenor, Knee-slap dance runs, tender ballad falsetto, Yricsation flow." },
  { key: "Trey Songz-birds", label: "Trey Songz-birds 🐦", real: "Trey Songz", gender: "MALE", style: "R&B vocals, seductive, emotional." },
  { key: "Ne-Yo-yo", label: "Ne-Yo-yo 🪀", real: "Ne-Yo", gender: "MALE", style: "Smooth melodic falsetto, silky R&B smoothness, smooth writer's delivery." },
  { key: "Mario-kart", label: "Mario-kart 🏎️", real: "Mario", gender: "MALE", style: "R&B vocals, early 2000s, smooth." },
  { key: "Omarion-ette", label: "Omarion-ette 🎭", real: "Omarion", gender: "MALE", style: "R&B vocals, dance, funky." },
  { key: "Bow Wow-wow", label: "Bow Wow-wow 🐕", real: "Bow Wow", gender: "MALE", style: "Rap vocals, youthful, pop-rap." },
  { key: "Soulja Boy-tell-em", label: "Soulja Boy-tell-em 🎮", real: "Soulja Boy", gender: "MALE", style: "Rap vocals, dance, crunk influence." },
  { key: "T-Pain-killer", label: "T-Pain-killer 💊", real: "T-Pain", gender: "MALE", style: "Heavy auto-tune Effect, club anthem, T-Pain tavern twang, karaoke machine." },
  { key: "Akon-vict", label: "Akon-vict ⚖️", real: "Akon", gender: "MALE", style: "Senegalese accent, stadium R&B, Konvicted crossover, automatic auto-tune." },
  { key: "Sean Paul-bearer", label: "Sean Paul-bearer ⚰️", real: "Sean Paul", gender: "MALE", style: "Dancehall ragga delivery, Jamaican patois, Get Busy rhythm, temperature energy." },
  { key: "Shag-gy", label: "Shag-gy 🐕", real: "Shaggy", gender: "MALE", style: "Dancehall reggae voice, It wasn't me comedic, Caribbean breezy, angel radio." },
  { key: "Queen Bee", label: "Queen Bee 🐝", real: "Beyoncé", gender: "FEMALE", style: "Diva power vocals, Single Ladies punch, Formation Texas swagger,flawless run." },
  { key: "Prince Charming", label: "Prince Charming 🤴", real: "Prince", gender: "MALE", style: "Falsetto, funk rock, sexual energy." },
  { key: "Madonna Kebab", label: "Madonna Kebab 🥙", real: "Madonna", gender: "FEMALE", style: "Breathy modal voice, seductive whisper verses, powerful belted chorus, dance-pop inflection." },
  { key: "Nirvan-nah", label: "Nirvan-nah 😴", real: "Nirvana", gender: "MALE", style: "Kurt Cobain anguished scream, grunge distortion, Smells Like Teen Spirit raw energy." },
  { key: "Led Zepp-lin", label: "Led Zepp-lin 🎈", real: "Led Zeppelin", gender: "MALE", style: "Robert Plant powerful screams, high falsetto wail, bluesy swagger, Stairway to Heaven drama." },
  { key: "Pink Floyd-ian", label: "Pink Floyd-ian 🧱", real: "Pink Floyd", gender: "MALE", style: "David Gilmour atmospheric vocals,Comfortably Numb soaring solos, psychedelic space rock, breathing." },
  { key: "The Rolling Scones", label: "The Rolling Scones 🍪", real: "The Rolling Stones", gender: "MALE", style: "Mick Jagger bluesy rasp, Satisfaction swagger, rock and roll grittiness, bad boy energy." },
  { key: "Johnny Cash-Register", label: "Johnny Cash-Register 🧾", real: "Johnny Cash", gender: "MALE", style: "Deep baritone, country storytelling, raw authenticity." },
  { key: "Frank Sin-atra", label: "Frank Sin-atra 🎙️", real: "Frank Sinatra", gender: "MALE", style: "Smooth crooner baritone, My Way standards, Rat Pack elegance, bossa nova whisper." },
  { key: "Bob Dylan-dog", label: "Bob Dylan-dog 🐕", real: "Bob Dylan", gender: "MALE", style: "Nasal folk drone, poetic mumble, Blowin' in the Wind protest, Mr. Tambourine Man campfire." },
  { key: "Jimi Hen-drix", label: "Jimi Hen-drix 🎸", real: "Jimi Hendrix", gender: "MALE", style: "Psychedelic rock, guitar god, visionary." },
  { key: "The Who-owl", label: "The Who-owl 🦉", real: "The Who", gender: "MALE", style: "Roger Townshend power screams, Tommy rock opera,Baba O'Riley anthemic energy." },
  { key: "The Doors-knobs", label: "The Doors-knobs 🚪", real: "The Doors", gender: "MALE", style: "Jim Morrison baritone mystique, Light My Fire seductive, LA Woman swamp blues, poetry slam." },
  { key: "Fleetwood Mac-n-Cheese", label: "Fleetwood Mac-n-Cheese 🧀", real: "Fleetwood Mac", gender: "MALE", style: "Stevie Nicks witchy whisper, Lindsey Buckingham guitar harmonies, Rumours drama,Go Your Own Way power." },
  { key: "Aerosmith-ereens", label: "Aerosmith-ereens ✈️", real: "Aerosmith", gender: "MALE", style: "Steven Tyler distinctive rasp, Livin' on the Edge screams, Aerosmith bluesy hard rock, I Don't Want to Miss a Thing ballad." },
  { key: "AC/DC-Adapter", label: "AC/DC-Adapter 🔌", real: "AC/DC", gender: "MALE", style: "Brian Johnson growling hard rock, Back in Black energy, Highway to Hell hellraiser." },
  { key: "Guns N' Roses-bushes", label: "Guns N' Roses-bushes 🌹", real: "Guns N' Roses", gender: "MALE", style: "Axl Rose high-range screams, Sweet Child O' Mine iconic, Welcome to the Jungle raw, November Rain drama." },
  { key: "Bruce Spring-steen", label: "Bruce Spring-steen 🚗", real: "Bruce Springsteen", gender: "MALE", style: "Gruff Jersey baritone, Born in the USA working class, Streets of Philadelphia storytelling, Nebraska raw." },
  { key: "Elton John-Deere", label: "Elton John-Deere 🚜", real: "Elton John", gender: "MALE", style: "Your Song flamboyant piano, Rocket Man ethereal falsetto, Crocodile Rock flamboyance, powerful dynamic range." },
  { key: "Stevie Wonder-bread", label: "Stevie Wonder-bread 🍞", real: "Stevie Wonder", gender: "MALE", style: "Superstition funk bass, Isn’t She Lovely angelic, harmonica virtuoso, Talking Book soul, I Just Called To Say I Love You romantic." },
  { key: "Marvin Gaye-lord", label: "Marvin Gaye-lord 👑", real: "Marvin Gaye", gender: "MALE", style: "Sexual Healing sensual whisper, What's Going On socially conscious, velvet Prince vibe, Let's Get It On seduction." },
  { key: "Aretha Frank-lin", label: "Aretha Frank-lin 💵", real: "Aretha Franklin", gender: "FEMALE", style: "RESPECT diva power, gospel-trained roar, natural woman soul, chain of Fools attitude." },
  { key: "James Brown-ie", label: "James Brown-ie 🍫", real: "James Brown", gender: "MALE", style: "Pappa's Got a Brand New Bag funk, Sex Machine relentless, raw grunts, tell me get up offa that thang." },
  { key: "Ray Charles-ton", label: "Ray Charles-ton 💃", real: "Ray Charles", gender: "MALE", style: "Georgia on My Mind soulful, Genius jazz crossover,What'd I Say raw gospel, unseeing vocal power." },
  { key: "Chuck Berry-pie", label: "Chuck Berry-pie 🥧", real: "Chuck Berry", gender: "MALE", style: "Rock and roll pioneer, guitar-driven." },
  { key: "Little Richard-son", label: "Little Richard-son 🏠", real: "Little Richard", gender: "MALE", style: "Rock and roll, flamboyant, high energy." },
  { key: "Buddy Holly-wood", label: "Buddy Holly-wood 🎬", real: "Buddy Holly", gender: "MALE", style: "Early rock and roll, wholesome, melodic." },
  { key: "Jerry Lee Lewis-iana", label: "Jerry Lee Lewis-iana 🐊", real: "Jerry Lee Lewis", gender: "MALE", style: "Rock and roll, piano, wildman." },
  { key: "Fats Domino-pizza", label: "Fats Domino-pizza 🍕", real: "Fats Domino", gender: "MALE", style: "New Orleans R&B, smooth, piano-driven." },
  { key: "Bo Diddley-squat", label: "Bo Diddley-squat 🏋️", real: "Bo Diddley", gender: "MALE", style: "Rock and roll, rhythm distinctive, raw." },
  { key: "Muddy Waters-slide", label: "Muddy Waters-slide 🛝", real: "Muddy Waters", gender: "MALE", style: "Delta blues, slide guitar, raw." },
  { key: "B.B. King-kong", label: "B.B. King-kong 🦍", real: "B.B. King", gender: "MALE", style: "Blues guitar, smooth vocals, expressive." },
  { key: "John Lee Hooker-rug", label: "John Lee Hooker-rug 🧶", real: "John Lee Hooker", gender: "MALE", style: "Blues, hypnotic, raw." },
  { key: "Howlin' Wolf-man", label: "Howlin' Wolf-man 🐺", real: "Howlin' Wolf", gender: "MALE", style: "Blues, powerful, menacing." },
  { key: "Etta James-bond", label: "Etta James-bond 🕵️", real: "Etta James", gender: "FEMALE", style: "Soul, powerful, gutbucket." },
  { key: "Billie Holi-day", label: "Billie Holi-day 🌺", real: "Billie Holiday", gender: "FEMALE", style: "Jazz vocals, melancholic, iconic." },
  { key: "Ella Fitz-gerald", label: "Ella Fitz-gerald 📚", real: "Ella Fitzgerald", gender: "FEMALE", style: "Jazz vocals, scat, flawless technique." },
  { key: "Louis Arm-strong", label: "Louis Arm-strong 💪", real: "Louis Armstrong", gender: "MALE", style: "Jazz trumpet, gravelly vocals, charismatic." },
  { key: "Duke Elling-ton", label: "Duke Elling-ton 🎹", real: "Duke Ellington", gender: "MALE", style: "Jazz big band, sophisticated, orchestral." },
  { key: "Count Basi-c", label: "Count Basi-c 🔢", real: "Count Basie", gender: "MALE", style: "Jazz big band, swing, piano-driven." },
  { key: "Miles Davis-cup", label: "Miles Davis-cup 🏆", real: "Miles Davis", gender: "MALE", style: "Jazz trumpet, cool, innovative." },
  { key: "John Col-trane", label: "John Col-trane 🚂", real: "John Coltrane", gender: "MALE", style: "Jazz saxophone, avant-garde, spiritual." },
  { key: "Charlie Par-ker", label: "Charlie Par-ker 🦜", real: "Charlie Parker", gender: "MALE", style: "Jazz saxophone, bebop, virtuoso." },
  { key: "Thelonious Monk-ey", label: "Thelonious Monk-ey 🐒", real: "Thelonious Monk", gender: "MALE", style: "Jazz piano, angular, unique." },
  { key: "Dizzy Gilles-pie", label: "Dizzy Gilles-pie 🥧", real: "Dizzy Gillespie", gender: "MALE", style: "Jazz trumpet, bebop, virtuoso." },
  { key: "Charles Min-gus", label: "Charles Min-gus 🎻", real: "Charles Mingus", gender: "MALE", style: "Jazz bass, composer, innovative." },
  { key: "Buddy Rich-ard", label: "Buddy Rich-ard 💰", real: "Buddy Rich", gender: "MALE", style: "Jazz drums, virtuoso, technical." },
  { key: "Gene Kru-pa", label: "Gene Kru-pa 🥁", real: "Gene Krupa", gender: "MALE", style: "Jazz drums, big band, energetic." },
  { key: "Benny Good-man", label: "Benny Good-man 👍", real: "Benny Goodman", gender: "MALE", style: "Jazz clarinet, swing, King of Swing." },
  { key: "Glenn Mil-ler", label: "Glenn Mil-ler 🌾", real: "Glenn Miller", gender: "MALE", style: "Jazz big band, swing, smooth." },
  { key: "Harry James-on", label: "Harry James-on 🎺", real: "Harry James", gender: "MALE", style: "Jazz trumpet, big band, powerful." },
  { key: "Bing Cros-by", label: "Bing Cros-by 🎄", real: "Bing Crosby", gender: "MALE", style: "Crooner, smooth, classic pop." },
  { key: "Nat King Cole-slaw", label: "Nat King Cole-slaw 🥗", real: "Nat King Cole", gender: "MALE", style: "Crooner, smooth piano, velvet voice." },
  { key: "Dean Mar-tin", label: "Dean Mar-tin 🍸", real: "Dean Martin", gender: "MALE", style: "Crooner, smooth, Italian charm." },
  { key: "Sammy Davis Jr-mint", label: "Sammy Davis Jr-mint 🍬", real: "Sammy Davis Jr", gender: "MALE", style: "Entertainer, smooth, Rat Pack." },
  { key: "Tony Ben-nett", label: "Tony Ben-nett 🎤", real: "Tony Bennett", gender: "MALE", style: "Crooner, jazz standards, elegant." },
  { key: "Frankie Ava-lon", label: "Frankie Ava-lon 🏖️", real: "Frankie Avalon", gender: "MALE", style: "Pop crooner, teen idol, smooth." },
  { key: "Bobby Dar-in", label: "Bobby Dar-in 🌊", real: "Bobby Darin", gender: "MALE", style: "Swashbuckling, smooth, multi-genre." },
  { key: "Ricky Nel-son", label: "Ricky Nel-son 🎯", real: "Ricky Nelson", gender: "MALE", style: "Teen idol, rock and roll, wholesome." },
  { key: "The Everly Broth-ers", label: "The Everly Broth-ers 👬", real: "The Everly Brothers", gender: "MALE", style: "Harmony duo, rock and roll, sweet." },
  { key: "Roy Orbi-son", label: "Roy Orbi-son 👓", real: "Roy Orbison", gender: "MALE", style: "Ballads, dramatic, operatic voice." },
  { key: "Carl Per-kins", label: "Carl Per-kins 🍔", real: "Carl Perkins", gender: "MALE", style: "Rock and roll, Sun Records, bluesy." },
  { key: "Gene Vin-cent", label: "Gene Vin-cent 🎸", real: "Gene Vincent", gender: "MALE", style: "Rock and roll, wild, BE-BOP-A-LULA." },
  { key: "Eddie Coch-ran", label: "Eddie Coch-ran 🐓", real: "Eddie Cochran", gender: "MALE", style: "Rock and roll, guitar-driven, rebellious." },
  { key: "Ritchie Val-ens", label: "Ritchie Val-ens 💃", real: "Ritchie Valens", gender: "MALE", style: "Rock and roll, Latin influence, sweet." },
  { key: "Del Shan-non", label: "Del Shan-non 📻", real: "Del Shannon", gender: "MALE", style: "Rock and roll, falsetto, pop." },
  { key: "Chubby Check-er", label: "Chubby Check-er ✅", real: "Chubby Checker", gender: "MALE", style: "R&B, twist, danceable." },
  { key: "Fats Wall-er", label: "Fats Wall-er 🧱", real: "Fats Waller", gender: "MALE", style: "Jazz piano, boogie-woogie, witty." },
  { key: "Sam Cooke-ie", label: "Sam Cooke-ie 🍪", real: "Sam Cooke", gender: "MALE", style: "Soul, smooth, gospel roots." },
  { key: "Otis Red-ding", label: "Otis Red-ding 🔔", real: "Otis Redding", gender: "MALE", style: "Soul, raw emotion, powerful." },
  { key: "Wilson Pick-ett", label: "Wilson Pick-ett 🪦", real: "Wilson Pickett", gender: "MALE", style: "Soul, energetic, raw." },
  { key: "Solomon Burke-ley", label: "Solomon Burke-ley 🏰", real: "Solomon Burke", gender: "MALE", style: "Soul, gospel-influenced, King of Soul." },
  { key: "Percy Sledge-hammer", label: "Percy Sledge-hammer 🔨", real: "Percy Sledge", gender: "MALE", style: "Soul ballads, emotional, When a Man Loves a Woman." },
  { key: "Joe Tex-as", label: "Joe Tex-as 🤠", real: "Joe Tex", gender: "MALE", style: "Soul, humorous, danceable." },
  { key: "Ziggy Mar-ley", label: "Ziggy Mar-ley ⭐", real: "Ziggy Marley", gender: "MALE", style: "Reggae, playful, Bob's son." },
  { key: "Damian Mar-ley", label: "Damian Mar-ley 🦁", real: "Damian Marley", gender: "MALE", style: "Reggae, modern, Bob's son." },
  { key: "Ky-Mani Mar-ley", label: "Ky-Mani Mar-ley 🎸", real: "Ky-Mani Marley", gender: "MALE", style: "Reggae, acoustic, roots." },
  { key: "Rita Mar-ley", label: "Rita Mar-ley 👑", real: "Rita Marley", gender: "FEMALE", style: "Reggae, soulful, Bob's wife." },
  { key: "Lauryn Hill-side", label: "Lauryn Hill-side 🏔️", real: "Lauryn Hill", gender: "FEMALE", style: "Neo-soul, conscious rap, powerful." },
  { key: "Wyclef Jean-jacket", label: "Wyclef Jean-jacket 🧥", real: "Wyclef Jean", gender: "MALE", style: "Hip-hop, Fugees, Caribbean." },
  { key: "Pras Mi-chel", label: "Pras Mi-chel 🥐", real: "Pras Michel", gender: "MALE", style: "Hip-hop, Fugees, multilingual." },
  { key: "Outkast-aways", label: "Outkast-aways 🚀", real: "OutKast", gender: "MALE", style: "Southern hip-hop, eclectic, Andre 3000 & Big Boi." },
  { key: "Andre 3000-lbs", label: "Andre 3000-lbs 🏋️", real: "Andre 3000", gender: "MALE", style: "Southern hip-hop, artistic, lyrical." },
  { key: "Big Boi-ardee", label: "Big Boi-ardee 🍝", real: "Big Boi", gender: "MALE", style: "Southern hip-hop, versatile, OutKast." },
  { key: "Wu-Tang Clan-destine", label: "Wu-Tang Clan-destine 🥷", real: "Wu-Tang Clan", gender: "MALE", style: "East Coast hip-hop, hard, kung fu samples." },
  { key: "RZA-razor", label: "RZA-razor 🪒", real: "RZA", gender: "MALE", style: "Wu-Tang founder, producer, gravelly." },
  { key: "GZA-gizzard", label: "GZA-gizzard 🦎", real: "GZA", gender: "MALE", style: "Wu-Tang, lyrical, methodical." },
  { key: "Method Man-nequin", label: "Method Man-nequin 🧍", real: "Method Man", gender: "MALE", style: "Wu-Tang, deep voice, catchy." },
  { key: "Ghostface Kill-ah", label: "Ghostface Kill-ah 👻", real: "Ghostface Killah", gender: "MALE", style: "Wu-Tang, dramatic, verbose." },
  { key: "Raekwon-do", label: "Raekwon-do 🥋", real: "Raekwon", gender: "MALE", style: "Wu-Tang, storytelling, vivid." },
  { key: "U-God-zilla", label: "U-God-zilla 🦖", real: "U-God", gender: "MALE", style: "Wu-Tang, deep voice, raw." },
  { key: "Goodie Mob-ster", label: "Goodie Mob-ster 🕵️", real: "Goodie Mob", gender: "MALE", style: "Southern hip-hop, conscious, Dungeon Family." },
  { key: "CeeLo Green-ery", label: "CeeLo Green-ery 🌿", real: "CeeLo Green", gender: "MALE", style: "Soulful, quirky, Goodie Mob/Gnarls Barkley." },
  { key: "Danger Mouse-trap", label: "Danger Mouse-trap 🧀", real: "Danger Mouse", gender: "MALE", style: "Producer, Gnarls Barkley, innovative." },
  { key: "MF DOOM-SDAY", label: "MF DOOM-SDAY 🎭", real: "MF DOOM", gender: "MALE", style: "Underground hip-hop, mask, complex." },
  { key: "Inspectah Deck-chair", label: "Inspectah Deck-chair 🪑", real: "Inspectah Deck", gender: "MALE", style: "Wu-Tang, versatile, underrated." },
  { key: "Clyde McPhat-ter", label: "Clyde McPhat-ter 🎤", real: "Clyde McPhatter", gender: "MALE", style: "R&B, high voice, early soul." },
  { key: "Jackie Wil-son", label: "Jackie Wil-son 🌙", real: "Jackie Wilson", gender: "MALE", style: "Soul, high energy, dynamic." },
  { key: "Cab Cal-loway", label: "Cab Cal-loway 🎩", real: "Cab Calloway", gender: "MALE", style: "Jazz, big band, hi-de-ho." },
  { key: "Louis Jor-dan", label: "Louis Jor-dan 👟", real: "Louis Jordan", gender: "MALE", style: "R&B, jump blues, sax-driven." },
  { key: "Big Joe Turn-er", label: "Big Joe Turn-er 🔄", real: "Big Joe Turner", gender: "MALE", style: "Blues, rock and roll pioneer, boogie." },
  { key: "Ruth Brown-ie", label: "Ruth Brown-ie 🍫", real: "Ruth Brown", gender: "FEMALE", style: "R&B, powerful, Atlantic Records." },
  { key: "LaVern Bak-er", label: "LaVern Bak-er 🥖", real: "LaVern Baker", gender: "FEMALE", style: "R&B, playful, Soul train." },
  { key: "Gnarls Bark-ley", label: "Gnarls Bark-ley 🤪", real: "Gnarls Barkley", gender: "MALE", style: "Soul, quirky, innovative, crazy sexiness." },
  { key: "Tommy Dor-sey", label: "Tommy Dor-sey 🎺", real: "Tommy Dorsey", gender: "MALE", style: "Jazz trombone, smooth, big band." },
  { key: "Cold-play-doh", label: "Cold-play-doh ❄️", real: "Coldplay", gender: "MALE", style: "Anthemic alternative rock, soaring falsetto, piano-driven emotion." },
  { key: "Imagine Drag-ons", label: "Imagine Drag-ons 🐉", real: "Imagine Dragons", gender: "MALE", style: "Arena rock, powerful drums, anthemic choruses." },
  { key: "Maroon 5-Alive", label: "Maroon 5-Alive 🍋", real: "Maroon 5", gender: "MALE", style: "Funky pop rock, smooth falsetto, radio-friendly." },
  { key: "One Direc-tion", label: "One Direc-tion ➡️", real: "One Direction", gender: "MALE", style: "Boy band pop, harmonies, youthful energy." },
  { key: "Linkin Park-ing", label: "Linkin Park-ing 🅿️", real: "Linkin Park", gender: "MALE", style: "Nu metal rap rock, emotional, hybrid theory energy." },
  { key: "Green Day-light", label: "Green Day-light 🌿", real: "Green Day", gender: "MALE", style: "Punk rock, fast power chords, snotty vocals." },
  { key: "Red Hot Chili Pepp-er", label: "Red Hot Chili Pepp-er 🌶️", real: "Red Hot Chili Peppers", gender: "MALE", style: "Funk rock, slap bass, Anthony Kiedis rap-singing." },
  { key: "Oasis-sis", label: "Oasis-sis 🌴", real: "Oasis", gender: "MALE", style: "Britpop, Liam Gallagher nasal snarl, Noel melodies." },
  { key: "Radio-head-ache", label: "Radio-head-ache 📻", real: "Radiohead", gender: "MALE", style: "Alternative rock, Thom Yorke falsetto, experimental." },
  { key: "Pearl Jam-boree", label: "Pearl Jam-boree 🍇", real: "Pearl Jam", gender: "MALE", style: "Grunge, Eddie Vedder baritone, earnest intensity." },
  { key: "Foo Fight-ers", label: "Foo Fight-ers ✈️", real: "Foo Fighters", gender: "MALE", style: "Arena rock, Dave Grohl raw vocals, powerful drums." },
  { key: "The Kill-ers", label: "The Kill-ers 🔪", real: "The Killers", gender: "MALE", style: "New wave rock, Brandon Flowers dramatic tenor, synths." },
  { key: "Panic! At The Disco-ball", label: "Panic! At The Disco-ball 🪩", real: "Panic! At The Disco", gender: "MALE", style: "Theatrical pop rock, Brendon Urie soaring vocals." },
  { key: "Fall Out Boy-band", label: "Fall Out Boy-band 👦", real: "Fall Out Boy", gender: "MALE", style: "Pop punk, Patrick Stump high tenor, wordplay lyrics." },
  { key: "My Chemi-cal Romance", label: "My Chemi-cal Romance 🧪", real: "My Chemical Romance", gender: "MALE", style: "Emo rock, Gerard Way dramatic delivery, anthemic." },
  { key: "Twenty One Pilot-s", label: "Twenty One Pilot-s ✈️", real: "Twenty One Pilots", gender: "MALE", style: "Genre-blending, Tyler Joseph rap-singing, emotional." },
  { key: "Paramore-ange", label: "Paramore-ange 🍊", real: "Paramore", gender: "FEMALE", style: "Pop punk, Hayley Williams powerful belter, energetic." },
  { key: "Evanes-cents", label: "Evanes-cents 🪙", real: "Evanescence", gender: "FEMALE", style: "Gothic rock, Amy Lee ethereal operatic vocals, dark." },
  { key: "System Of A Down-town", label: "System Of A Down-town 🏙️", real: "System of a Down", gender: "MALE", style: "Nu metal, Serj Tankian unhinged vocals, political." },
  { key: "Slip-knot", label: "Slip-knot 🪢", real: "Slipknot", gender: "MALE", style: "Heavy metal, Corey Taylor aggressive growls, chaotic." },
  { key: "Metalli-ca", label: "Metalli-ca 🥫", real: "Metallica", gender: "MALE", style: "Thrash metal, James Hetfield rhythmic barking, heavy." },
  { key: "Iron Maid-en", label: "Iron Maid-en 👗", real: "Iron Maiden", gender: "MALE", style: "Heavy metal, Bruce Dickinson operatic wail, galloping." },
  { key: "Black Sab-bath", label: "Black Sab-bath 🕯️", real: "Black Sabbath", gender: "MALE", style: "Doom metal, Ozzy Osbourne haunting wail, dark riffs." },
  { key: "Deep Pur-ple", label: "Deep Pur-ple 🍇", real: "Deep Purple", gender: "MALE", style: "Hard rock, Ian Gillan powerful screams, organ-driven." },
  { key: "Journey-man", label: "Journey-man 🚂", real: "Journey", gender: "MALE", style: "Arena rock, Steve Perry soaring tenor, anthemic power ballads." },
  { key: "Bon Jovi-al", label: "Bon Jovi-al 😄", real: "Bon Jovi", gender: "MALE", style: "Hair metal, Jon Bon Jovi raspy tenor, big choruses." },
  { key: "Def Lepp-ard", label: "Def Lepp-ard 🐆", real: "Def Leppard", gender: "MALE", style: "Glam metal, Joe Elliott rasp, layered harmonies." },
  { key: "Whitney Houston-we", label: "Whitney Houston-we 🚀", real: "Whitney Houston", gender: "FEMALE", style: "Powerhouse pop-R&B, incredible range, gospel roots." },
  { key: "Celine Dion-saur", label: "Celine Dion-saur 🦕", real: "Celine Dion", gender: "FEMALE", style: "Power ballads, soaring crystalline vocals, dramatic." },
  { key: "Mariah Care-ybear", label: "Mariah Care-ybear 🐻", real: "Mariah Carey", gender: "FEMALE", style: "Pop-R&B, whistle register, melismatic runs." },
  { key: "Jennifer Lopez-ture", label: "Jennifer Lopez-ture 🍑", real: "Jennifer Lopez", gender: "FEMALE", style: "Latin pop, dance-pop, confident diva energy." },
  { key: "Shakira-misu", label: "Shakira-misu 🍰", real: "Shakira", gender: "FEMALE", style: "Latin pop, unique yodel-like vocal texture, hip shakes." },
  { key: "Enrique Igle-sias", label: "Enrique Igle-sias 🦅", real: "Enrique Iglesias", gender: "MALE", style: "Latin pop, romantic ballads, smooth vocals." },
  { key: "Pit-bull", label: "Pit-bull 🐕", real: "Pitbull", gender: "MALE", style: "Latin-infused pop rap, party anthems, Mr. Worldwide." },
  { key: "Daddy Yan-kee", label: "Daddy Yan-kee 🧢", real: "Daddy Yankee", gender: "MALE", style: "Reggaeton, fast flow, dembow rhythms, King of Reggaeton." },
  { key: "Bad Bun-ny", label: "Bad Bun-ny 🐰", real: "Bad Bunny", gender: "MALE", style: "Latin trap, reggaeton, deep monotone vocals, Puerto Rican." },
  { key: "Karol G-Force", label: "Karol G-Force 💅", real: "Karol G", gender: "FEMALE", style: "Reggaeton, Latin pop, empowering female vocals." },
  { key: "Rosalía-mond", label: "Rosalía-mond 💃", real: "Rosalía", gender: "FEMALE", style: "Flamenco pop, experimental production, unique vocal style." },
  { key: "Malu-ma", label: "Malu-ma 👩", real: "Maluma", gender: "MALE", style: "Reggaeton, Latin pop, smooth romantic vocals." },
  { key: "J Bal-vin", label: "J Bal-vin 🌈", real: "J Balvin", gender: "MALE", style: "Reggaeton, colorful aesthetic, melodic flow." },
  { key: "Ozuna-mi", label: "Ozuna-mi 🌊", real: "Ozuna", gender: "MALE", style: "Reggaeton, Latin trap, melodic high-pitched vocals." },
  { key: "Anuel AA-battery", label: "Anuel AA-battery 🔋", real: "Anuel AA", gender: "MALE", style: "Latin trap, reggaeton, gritty vocals, Real Hasta La Muerte." },
  { key: "Nicky Jam-bon", label: "Nicky Jam-bon 🍖", real: "Nicky Jam", gender: "MALE", style: "Reggaeton, romantic reggaeton, smooth vocals." },
  { key: "Farru-ko", label: "Farru-ko 🐸", real: "Farruko", gender: "MALE", style: "Reggaeton, Latin trap, energetic party anthems." },
  { key: "Luis Fon-si", label: "Luis Fon-si 🎵", real: "Luis Fonsi", gender: "MALE", style: "Latin pop, romantic ballads, smooth tenor." },
  { key: "Ricky Mar-tian", label: "Ricky Mar-tian 👽", real: "Ricky Martin", gender: "MALE", style: "Latin pop, energetic, Livin' La Vida Loca vibes." },
  { key: "Marc Anthon-y", label: "Marc Anthon-y 🌹", real: "Marc Anthony", gender: "MALE", style: "Salsa, Latin pop, powerful romantic vocals." },
  { key: "Gloria Estefan-t", label: "Gloria Estefan-t 💃", real: "Gloria Estefan", gender: "FEMALE", style: "Latin pop, conga rhythms, powerful uplifting vocals." },
  { key: "Gloria Gay-nor", label: "Gloria Gay-nor 🌈", real: "Gloria Gaynor", gender: "FEMALE", style: "Disco, powerful vocals, I Will Survive anthem energy." },
  { key: "Donna Sum-mer", label: "Donna Sum-mer ☀️", real: "Donna Summer", gender: "FEMALE", style: "Disco queen, powerful vocals, dance floor anthems." },
  { key: "Bee Gee-whiz", label: "Bee Gee-whiz 🤠", real: "Bee Gees", gender: "MALE", style: "Disco falsetto, tight harmonies, Saturday Night Fever." },
  { key: "ABBA-cadabra", label: "ABBA-cadabra 🪄", real: "ABBA", gender: "FEMALE", style: "Disco pop, Swedish harmonies, catchy melodies." },
  { key: "Dolly Par-ton", label: "Dolly Par-ton 🎸", real: "Dolly Parton", gender: "FEMALE", style: "Country, sweet soprano, storytelling, iconic." },
  { key: "Shania Twain-train", label: "Shania Twain-train 🚂", real: "Shania Twain", gender: "FEMALE", style: "Country pop, confident female vocals, crossover appeal." },
  { key: "Garth Brooks-brothers", label: "Garth Brooks-brothers 🤠", real: "Garth Brooks", gender: "MALE", style: "Country, powerful baritone, arena country energy." },
  { key: "Kenny Ches-ney", label: "Kenny Ches-ney 🏝️", real: "Kenny Chesney", gender: "MALE", style: "Country, beach vibes, laid-back storytelling." },
  { key: "Tim McGraw-l", label: "Tim McGraw-l 😠", real: "Tim McGraw", gender: "MALE", style: "Country, smooth baritone, romantic ballads." },
  { key: "Faith Hill-side", label: "Faith Hill-side 🏔️", real: "Faith Hill", gender: "FEMALE", style: "Country pop, powerful vocals, crossover appeal." },
  { key: "Carrie Under-wood", label: "Carrie Under-wood 🪵", real: "Carrie Underwood", gender: "FEMALE", style: "Country, powerhouse vocals, American Idol winner." },
  { key: "Keith Ur-ban", label: "Keith Ur-ban 🏙️", real: "Keith Urban", gender: "MALE", style: "Country rock, guitar virtuoso, Australian twang." },
  { key: "Blake Shel-ton", label: "Blake Shel-ton 🐚", real: "Blake Shelton", gender: "MALE", style: "Country, deep baritone, traditional country sound." },
  { key: "Luke Bryan-t", label: "Luke Bryan-t 🦌", real: "Luke Bryan", gender: "MALE", style: "Bro-country, party anthems, smooth vocals." },
  { key: "Jason Aldean-mal", label: "Jason Aldean-mal 🦓", real: "Jason Aldean", gender: "MALE", style: "Country rock, edgy vocals, modern country." },
  { key: "Florida Georgia Line-d", label: "Florida Georgia Line-d 📏", real: "Florida Georgia Line", gender: "MALE", style: "Bro-country, hip-hop influences, party anthems." },
  { key: "Thomas Rhett-oric", label: "Thomas Rhett-oric 🎤", real: "Thomas Rhett", gender: "MALE", style: "Country pop, smooth vocals, romantic." },
  { key: "Sam Hunt-ing", label: "Sam Hunt-ing 🦌", real: "Sam Hunt", gender: "MALE", style: "Country, spoken-word style, pop influences." },
  { key: "Kane Brown-ie", label: "Kane Brown-ie 🍫", real: "Kane Brown", gender: "MALE", style: "Country R&B, smooth baritone, modern country." },
  { key: "Chris Staple-ton", label: "Chris Staple-ton 📎", real: "Chris Stapleton", gender: "MALE", style: "Southern soul country, gritty bluesy vocals, authentic." },
  { key: "Miranda Lam-bert", label: "Miranda Lam-bert 🐑", real: "Miranda Lambert", gender: "FEMALE", style: "Country, sassy storytelling, powerful female vocals." },
  { key: "Kacey Mus-graves", label: "Kacey Mus-graves 🌈", real: "Kacey Musgraves", gender: "FEMALE", style: "Country pop, psychedelic influences, clever lyrics." },
  { key: "Maren Mor-ris", label: "Maren Mor-ris 🚗", real: "Maren Morris", gender: "FEMALE", style: "Country pop, powerful vocals, crossover appeal." },
  { key: "Lady A-ntebellum", label: "Lady A-ntebellum 🏛️", real: "Lady A", gender: "FEMALE", style: "Country pop, harmonies, romantic ballads." },
  { key: "Little Big Town-hall", label: "Little Big Town-hall 🏛️", real: "Little Big Town", gender: "FEMALE", style: "Country harmonies, Kimberly Schlapman sweet vocals." },
  { key: "The Chains-mokers", label: "The Chains-mokers 🚬", real: "The Chainsmokers", gender: "MALE", style: "EDM pop, chilled drops, radio-friendly electronic." },
  { key: "Calvin Har-ris", label: "Calvin Har-ris 🐇", real: "Calvin Harris", gender: "MALE", style: "EDM, house, pop crossover, Scottish producer." },
  { key: "David Guet-ta", label: "David Guet-ta 🎧", real: "David Guetta", gender: "MALE", style: "EDM, big room house, festival anthems, French DJ." },
  { key: "Tiësto-rring", label: "Tiësto-rring 💍", real: "Tiësto", gender: "MALE", style: "Trance, EDM, progressive house, Dutch DJ legend." },
  { key: "Avicii-ron", label: "Avicii-ron ⚙️", real: "Avicii", gender: "MALE", style: "Melodic house, folk-EDM fusion, uplifting anthems." },
  { key: "Martin Gar-rix", label: "Martin Gar-rix 🦁", real: "Martin Garrix", gender: "MALE", style: "Big room house, energetic drops, Dutch DJ prodigy." },
  { key: "Zedd-icine", label: "Zedd-icine 💊", real: "Zedd", gender: "MALE", style: "Electro house, pop-EDM, melodic synths, Russian-German." },
  { key: "Diplo-mat", label: "Diplo-mat 🌍", real: "Diplo", gender: "MALE", style: "Electronic, dancehall, global bass, eclectic producer." },
  { key: "Major Laz-er", label: "Major Laz-er 🔫", real: "Major Lazer", gender: "MALE", style: "Electronic, dancehall, global party anthems." },
  { key: "Skril-lex", label: "Skril-lex 📚", real: "Skrillex", gender: "MALE", style: "Dubstep, brostep, heavy bass drops, electronic." },
  { key: "Dead-mau5", label: "Dead-mau5 🐭", real: "deadmau5", gender: "MALE", style: "Progressive house, techno, Canadian electronic producer." },
  { key: "Swedish House Mafia-fia", label: "Swedish House Mafia-fia 🇸🇪", real: "Swedish House Mafia", gender: "MALE", style: "Progressive house, anthemic EDM, Swedish supergroup." },
  { key: "Disclo-sure", label: "Disclo-sure 📂", real: "Disclosure", gender: "MALE", style: "UK garage, deep house, soulful electronic, brother duo." },
  { key: "Flume-id", label: "Flume-id 🌊", real: "Flume", gender: "MALE", style: "Future bass, experimental electronic, Australian producer." },
  { key: "Ky-go-go", label: "Ky-go-go 🌴", real: "Kygo", gender: "MALE", style: "Tropical house, piano melodies, relaxed beach vibes." },
  { key: "Alan Walk-er", label: "Alan Walk-er 🚶", real: "Alan Walker", gender: "MALE", style: "Melodic EDM, future bass, Norwegian producer." },
  { key: "Marsh-mello", label: "Marsh-mello 🍡", real: "Marshmello", gender: "MALE", style: "Future bass, pop-EDM, helmet-wearing DJ, melodic." },
  { key: "Illeni-um", label: "Illeni-um 🦋", real: "Illenium", gender: "MALE", style: "Melodic dubstep, future bass, emotional electronic." },
  { key: "Odes-za", label: "Odes-za 🌅", real: "ODESZA", gender: "MALE", style: "Chillwave, future bass, ethereal electronic duo." },
  { key: "Bon I-ver", label: "Bon I-ver 🦌", real: "Bon Iver", gender: "MALE", style: "Indie folk, auto-tuned falsetto, ethereal, Wisconsin." },
  { key: "Fleet Fox-es", label: "Fleet Fox-es 🦊", real: "Fleet Foxes", gender: "MALE", style: "Indie folk, lush harmonies, pastoral, Seattle." },
  { key: "Vampire Week-end", label: "Vampire Week-end 🧛", real: "Vampire Weekend", gender: "MALE", style: "Indie pop, Afro-pop influences, preppy intellectual lyrics." },
  { key: "Arcade Fire-extinguisher", label: "Arcade Fire-extinguisher 🧯", real: "Arcade Fire", gender: "MALE", style: "Indie rock, orchestral arrangements, anthemic Canadian collective." },
  { key: "The Strokes-brush", label: "The Strokes-brush 🖌️", real: "The Strokes", gender: "MALE", style: "Indie rock, Julian Casablancas cool drawl, New York." },
  { key: "Arctic Mon-keys", label: "Arctic Mon-keys 🐒", real: "Arctic Monkeys", gender: "MALE", style: "Indie rock, Alex Turner witty lyrics, Sheffield swagger." },
  { key: "Kings Of Leon-ardo", label: "Kings Of Leon-ardo 🦁", real: "Kings of Leon", gender: "MALE", style: "Southern rock, Caleb Followill raspy vocals, anthemic." },
  { key: "The Black Keys-board", label: "The Black Keys-board 🎹", real: "The Black Keys", gender: "MALE", style: "Blues rock, garage sound, Dan Auerbach gritty vocals." },
  { key: "White Strip-es", label: "White Strip-es 🍬", real: "The White Stripes", gender: "MALE", style: "Garage rock, Jack White raw bluesy howl, Detroit duo." },
  { key: "The Ra-conteurs", label: "The Ra-conteurs 📖", real: "The Raconteurs", gender: "MALE", style: "Rock, Jack White, Brendan Benson, power pop." },
  { key: "Jack White-out", label: "Jack White-out ❄️", real: "Jack White", gender: "MALE", style: "Garage rock, blues, raw vocals, guitar virtuoso." },
  { key: "Queens Of The Stone Age-nt", label: "Queens Of The Stone Age-nt 👑", real: "Queens of the Stone Age", gender: "MALE", style: "Stoner rock, Josh Homme desert groove, heavy riffs." },
  { key: "Muse-um", label: "Muse-um 🏛️", real: "Muse", gender: "MALE", style: "Alternative rock, Matt Bellamy falsetto, operatic grandeur." },
  { key: "Thirty Seconds To Mars-h", label: "Thirty Seconds To Mars-h 🚀", real: "Thirty Seconds to Mars", gender: "MALE", style: "Alternative rock, Jared Leto dramatic vocals, space themes." },
  { key: "A Day To Remem-ber", label: "A Day To Remem-ber 🧠", real: "A Day to Remember", gender: "MALE", style: "Pop punk metalcore, Jeremy McKinnon aggressive melodic." },
  { key: "Bring Me The Hori-zon", label: "Bring Me The Hori-zon 🌅", real: "Bring Me the Horizon", gender: "MALE", style: "Metalcore to pop rock, Oli Sykes scream-sing, Sheffield." },
  { key: "Avenged Seven-fold", label: "Avenged Seven-fold 🃏", real: "Avenged Sevenfold", gender: "MALE", style: "Heavy metal, M. Shadows gritty vocals, dual guitars." },
  { key: "Disturbed-sleep", label: "Disturbed-sleep 😴", real: "Disturbed", gender: "MALE", style: "Nu metal, David Draiman staccato bark, Down With The Sickness." },
  { key: "Korn-flakes", label: "Korn-flakes 🌽", real: "Korn", gender: "MALE", style: "Nu metal, Jonathan Davis scatting emotional vocals, bagpipes." },
  { key: "Limp Biz-kit", label: "Limp Biz-kit 🍪", real: "Limp Bizkit", gender: "MALE", style: "Nu metal, Fred Durst rap-rock, DJ Lethal scratches." },
  { key: "Rage Against The Machine-gun", label: "Rage Against The Machine-gun 🔫", real: "Rage Against the Machine", gender: "MALE", style: "Rap metal, Zack de la Rocha political fury, Tom Morello." },
  { key: "Audioslave-ment", label: "Audioslave-ment ⛓️", real: "Audioslave", gender: "MALE", style: "Hard rock, Chris Cornell soaring vocals, RATM rhythm section." },
  { key: "Soundgarden-hoe", label: "Soundgarden-hoe 🌱", real: "Soundgarden", gender: "MALE", style: "Grunge, Chris Cornell four-octave range, heavy riffs." },
  { key: "Alice In Chains-aw", label: "Alice In Chains-aw 🪚", real: "Alice in Chains", gender: "MALE", style: "Grunge, Layne Staley haunting harmonies, dark sludge." },
  { key: "Stone Temple Pil-ots", label: "Stone Temple Pil-ots ✈️", real: "Stone Temple Pilots", gender: "MALE", style: "Grunge, Scott Weiland dynamic vocals, 90s alternative." },
  { key: "Bush-wood", label: "Bush-wood 🌳", real: "Bush", gender: "MALE", style: "Grunge, Gavin Rossdale raspy vocals, British alternative." },
  { key: "Creed-ible", label: "Creed-ible 🦎", real: "Creed", gender: "MALE", style: "Post-grunge, Scott Stapp baritone rumble, Christian themes." },
  { key: "Nickel-back-pain", label: "Nickel-back-pain 🤕", real: "Nickelback", gender: "MALE", style: "Post-grunge, Chad Kroeger raspy rock vocals, radio rock." },
  { key: "Three Doors Down-town", label: "Three Doors Down-town 🚪", real: "3 Doors Down", gender: "MALE", style: "Post-grunge, Brad Arnold earnest vocals, emotional rock." },
  { key: "Matchbox Twenty-One", label: "Matchbox Twenty-One 🚗", real: "Matchbox Twenty", gender: "MALE", style: "Alternative rock, Rob Thomas soulful pop vocals, Florida." },
  { key: "Goo Goo Doll-ars", label: "Goo Goo Doll-ars 💵", real: "Goo Goo Dolls", gender: "MALE", style: "Alternative rock, John Rzeznik raspy vocals, power ballads." },
  { key: "The Cran-berries", label: "The Cran-berries 🍓", real: "The Cranberries", gender: "FEMALE", style: "Alternative rock, Dolores O'Riordan yodel-like vocals, Irish." },
  { key: "No Doubt-ful", label: "No Doubt-ful 🤔", real: "No Doubt", gender: "FEMALE", style: "Ska punk, Gwen Stefani powerful vocals, Anaheim." },
  { key: "Sublime-ime", label: "Sublime-ime 🍋", real: "Sublime", gender: "MALE", style: "Ska punk reggae, Bradley Nowell smooth vocals, Long Beach." },
  { key: "Reel Big Fish-bone", label: "Reel Big Fish-bone 🐟", real: "Reel Big Fish", gender: "MALE", style: "Ska punk, horns, energetic, Orange County." },
  { key: "Less Than Jake-gyllenhaal", label: "Less Than Jake-gyllenhaal 🎬", real: "Less Than Jake", gender: "MALE", style: "Ska punk, horns, fast energetic, Florida." },
  { key: "Gold-fin-ger", label: "Gold-fin-ger 🐠", real: "Goldfinger", gender: "MALE", style: "Ska punk, pop punk, energetic horns, Los Angeles." },
  { key: "The Off-spring", label: "The Off-spring 👶", real: "The Offspring", gender: "MALE", style: "Punk rock, Dexter Holland high vocals, Orange County." },
  { key: "Bad Reli-gion", label: "Bad Reli-gion ⛪", real: "Bad Religion", gender: "MALE", style: "Punk rock, Greg Graffin intellectual lyrics, harmonies." },
  { key: "Social Distor-tion", label: "Social Distor-tion 🌀", real: "Social Distortion", gender: "MALE", style: "Punk rock, Mike Ness rockabilly influence, Orange County." },
  { key: "Rancid-cid", label: "Rancid-cid 🧪", real: "Rancid", gender: "MALE", style: "Punk rock, Tim Armstrong gravelly vocals, Operation Ivy." },
  { key: "Penny-wise", label: "Penny-wise 🤡", real: "Pennywise", gender: "MALE", style: "Punk rock, fast melodic, Fletcher Dragge guitars." },
  { key: "Sum 41-teen", label: "Sum 41-teen 🎂", real: "Sum 41", gender: "MALE", style: "Pop punk, Deryck Whibley nasally vocals, Canadian." },
  { key: "Simple Plan-et", label: "Simple Plan-et 🌍", real: "Simple Plan", gender: "MALE", style: "Pop punk, Pierre Bouvier emotional vocals, Canadian." },
  { key: "New Found Glory-ous", label: "New Found Glory-ous 🌟", real: "New Found Glory", gender: "MALE", style: "Pop punk, Jordan Pundik pop vocals, Florida." },
  { key: "Yellow-card", label: "Yellow-card 🟨", real: "Yellowcard", gender: "MALE", style: "Pop punk, violin-driven, Ryan Key vocals, Florida." },
  { key: "Taking Back Sun-day", label: "Taking Back Sun-day ☀️", real: "Taking Back Sunday", gender: "MALE", style: "Emo, Adam Lazzara call-and-response vocals, Long Island." },
  { key: "Brand New-ton", label: "Brand New-ton 🍎", real: "Brand New", gender: "MALE", style: "Emo, Jesse Lacey introspective lyrics, Long Island." },
  { key: "Jimmy Eat World-wide", label: "Jimmy Eat World-wide 🌐", real: "Jimmy Eat World", gender: "MALE", style: "Emo pop rock, Jim Adkins earnest vocals, Arizona." },
  { key: "Death Cab For Cutie-pie", label: "Death Cab For Cutie-pie 🥧", real: "Death Cab for Cutie", gender: "MALE", style: "Indie rock, Ben Gibbard soft vocals, melancholic." },
  { key: "The Postal Serv-ice", label: "The Postal Serv-ice 📬", real: "The Postal Service", gender: "MALE", style: "Indie electronic, Ben Gibbard soft vocals, twee." },
  { key: "Modest Mouse-trap", label: "Modest Mouse-trap 🧀", real: "Modest Mouse", gender: "MALE", style: "Indie rock, Isaac Brock twitchy vocals, Pacific Northwest." },
  { key: "The Shins-plints", label: "The Shins-plints 🦵", real: "The Shins", gender: "MALE", style: "Indie pop, James Mercer high nasal vocals, Albuquerque." },
  { key: "Death From Above 1979-er", label: "Death From Above 1979-er 🥁", real: "Death from Above 1979", gender: "MALE", style: "Dance-punk, bass and drums duo, Toronto." },
  { key: "LCD Soundsys-tem", label: "LCD Soundsys-tem 💻", real: "LCD Soundsystem", gender: "MALE", style: "Dance-punk, James Murphy talk-sing, Brooklyn." },
  { key: "Hot Chip-munk", label: "Hot Chip-munk 🐿️", real: "Hot Chip", gender: "MALE", style: "Electropop, quirky, British synth-pop." },
  { key: "MGMT-ment", label: "MGMT-ment 📊", real: "MGMT", gender: "MALE", style: "Psychedelic pop, Andrew VanWyngarden falsetto, Connecticut." },
  { key: "Tame Impala-la", label: "Tame Impala-la 🦘", real: "Tame Impala", gender: "MALE", style: "Psychedelic pop, Kevin Parker dreamy production, Australian." },
  { key: "Portugal. The Man-nequin", label: "Portugal. The Man-nequin 🧍", real: "Portugal. The Man", gender: "MALE", style: "Indie rock, John Gourley high falsetto, Alaska." },
  { key: "Foster The Peo-ple", label: "Foster The Peo-ple 👥", real: "Foster the People", gender: "MALE", style: "Indie pop, Mark Foster falsetto, Pumped Up Kicks." },
  { key: "Young The Gi-ant", label: "Young The Gi-ant 🦶", real: "Young the Giant", gender: "MALE", style: "Indie rock, Sameer Gadhia soaring vocals, California." },
  { key: "Walk The Moon-landing", label: "Walk The Moon-landing 🚀", real: "Walk the Moon", gender: "MALE", style: "Indie pop, Nicholas Petricca energetic vocals, Shut Up And Dance." },
  { key: "Two Door Cinema Club-sandwich", label: "Two Door Cinema Club-sandwich 🥪", real: "Two Door Cinema Club", gender: "MALE", style: "Indie pop, Alex Trimble Irish vocals, danceable guitars." },
  { key: "Passion Pit-bull", label: "Passion Pit-bull 🐕", real: "Passion Pit", gender: "MALE", style: "Electropop, Michael Angelakos high falsetto, Massachusetts." },
  { key: "Phoenix-rising", label: "Phoenix-rising 🐦", real: "Phoenix", gender: "MALE", style: "Indie pop, Thomas Mars smooth French vocals, Paris." },
  { key: "French Kicks-ball", label: "French Kicks-ball ⚽", real: "French Kicks", gender: "MALE", style: "Indie rock, jangly guitars, New York." },
  { key: "The Rapture-ture", label: "The Rapture-ture 😇", real: "The Rapture", gender: "MALE", style: "Dance-punk, cowbell, New York." },
  { key: "Bloc Par-ty", label: "Bloc Par-ty 🎉", real: "Bloc Party", gender: "MALE", style: "Indie rock, Kele Okereke British vocals, danceable." },
  { key: "Inter-poll", label: "Inter-poll 📊", real: "Interpol", gender: "MALE", style: "Post-punk revival, Paul Banks baritone, New York." },
  { key: "Joy Divi-sion", label: "Joy Divi-sion ➗", real: "Joy Division", gender: "MALE", style: "Post-punk, Ian Curtis dramatic baritone, Manchester." },
  { key: "New Or-der", label: "New Or-der 📋", real: "New Order", gender: "MALE", style: "New wave, electronic, Bernard Sumner flat vocals, Manchester." },
  { key: "The Cure-ious", label: "The Cure-ious 🐱", real: "The Cure", gender: "MALE", style: "Gothic rock, Robert Smith mopey vocals, post-punk." },
  { key: "Depeche Mode-l", label: "Depeche Mode-l 🕶️", real: "Depeche Mode", gender: "MALE", style: "Synth-pop, dark wave, Dave Gahan deep baritone." },
  { key: "Pet Shop Boys-will-be-boys", label: "Pet Shop Boys-will-be-boys 🐕", real: "Pet Shop Boys", gender: "MALE", style: "Synth-pop, Neil Tennant deadpan vocals, British duo." },
  { key: "New Kids On The Block-chain", label: "New Kids On The Block-chain ⛓️", real: "New Kids on the Block", gender: "MALE", style: "Boy band, New Jack Swing, Boston." },
  { key: "Backstreet Boys-will-be-boys", label: "Backstreet Boys-will-be-boys 🐕", real: "Backstreet Boys", gender: "MALE", style: "Boy band, harmonies, Orlando pop." },
  { key: "NSYNC-hronized", label: "NSYNC-hronized 🔄", real: "NSYNC", gender: "MALE", style: "Boy band, Justin Timberlake lead, Orlando pop." },
  { key: "98 De-grees", label: "98 De-grees 🌡️", real: "98 Degrees", gender: "MALE", style: "Boy band, harmonies, adult contemporary." },
  { key: "Boyz II Men-tal", label: "Boyz II Men-tal 🧠", real: "Boyz II Men", gender: "MALE", style: "R&B harmonies, Philadelphia soul, ballads." },
  { key: "Jode-ci", label: "Jode-ci 🎤", real: "Jodeci", gender: "MALE", style: "R&B, new jack swing, gospel-influenced harmonies." },
  { key: "Bell Biv DeVoe-lution", label: "Bell Biv DeVoe-lution 🦎", real: "Bell Biv DeVoe", gender: "MALE", style: "New jack swing, hip-hop soul, Boston." },
  { key: "Color Me Badd-ly", label: "Color Me Badd-ly 🖍️", real: "Color Me Badd", gender: "MALE", style: "R&B harmonies, new jack swing, Oklahoma." },
  { key: "All-4-One", label: "All-4-One 🎵", real: "All-4-One", gender: "MALE", style: "R&B vocal group, harmonies, California." },
  { key: "Soul For Real-ly", label: "Soul For Real-ly 💯", real: "Soul For Real", gender: "MALE", style: "R&B harmonies, new jack swing, 90s." },
  { key: "Dru Hill-side", label: "Dru Hill-side 🏔️", real: "Dru Hill", gender: "MALE", style: "R&B, Sisqó lead vocals, Baltimore." },
  { key: "Silk-y", label: "Silk-y 🧣", real: "Silk", gender: "MALE", style: "R&B, smooth harmonies, Atlanta." },
  { key: "SWV-ery", label: "SWV-ery ⛓️", real: "SWV", gender: "FEMALE", style: "R&B, Coko powerful lead, harmonies, New York." },
  { key: "Total-ly", label: "Total-ly 💯", real: "Total", gender: "FEMALE", style: "R&B, Bad Boy Records, hip-hop soul." },
  { key: "702-nd", label: "702-nd 🎰", real: "702", gender: "FEMALE", style: "R&B, Las Vegas trio, Missy Elliott proteges." },
  { key: "Blaque-ey", label: "Blaque-ey 🎭", real: "Blaque", gender: "FEMALE", style: "R&B, Left Eye proteges, 90s girl group." },
  { key: "3LW-olves", label: "3LW-olves 🐺", real: "3LW", gender: "FEMALE", style: "R&B pop, teenage girl group, early 2000s." },
  { key: "Danity Kane-ine", label: "Danity Kane-ine 🐕", real: "Danity Kane", gender: "FEMALE", style: "R&B pop, Making the Band, harmonies." },
  { key: "Pussycat Doll-ars", label: "Pussycat Doll-ars 💵", real: "Pussycat Dolls", gender: "FEMALE", style: "Pop, burlesque, Nicole Scherzinger lead vocals." },
  { key: "Fifth Har-mony", label: "Fifth Har-mony 🎵", real: "Fifth Harmony", gender: "FEMALE", style: "Pop girl group, X Factor, Camila Cabello alumnae." },
  { key: "Little Mix-tape", label: "Little Mix-tape 📼", real: "Little Mix", gender: "FEMALE", style: "Pop girl group, X Factor winners, harmonies." },
  { key: "Spice Girls-night-out", label: "Spice Girls-night-out 🌃", real: "Spice Girls", gender: "FEMALE", style: "Pop girl group, British, Girl Power anthems." },
  { key: "Destiny's Child-ish", label: "Destiny's Child-ish 👶", real: "Destiny's Child", gender: "FEMALE", style: "R&B girl group, Beyoncé lead, Houston." },
  { key: "TLC-care", label: "TLC-care 🏥", real: "TLC", gender: "FEMALE", style: "R&B hip-hop, Atlanta, T-Boz Left Eye Chili." },
  { key: "En Vouge", label: "En Vouge 💃", real: "En Vogue", gender: "FEMALE", style: "R&B harmonies, Oakland, Funky Divas." },
  { key: "Salt-N-Pepa-rmint", label: "Salt-N-Pepa-rmint 🍬", real: "Salt-N-Pepa", gender: "FEMALE", style: "Hip-hop duo, Queens, Push It." },
  { key: "Eve-ryday", label: "Eve-ryday 📅", real: "Eve", gender: "FEMALE", style: "Hip-hop, Ruff Ryders, Philadelphia." },
  { key: "Missy Elli-ott", label: "Missy Elli-ott 🚂", real: "Missy Elliott", gender: "FEMALE", style: "Hip-hop, innovative production, Virginia." },
  { key: "Lil' Kim-chi", label: "Lil' Kim-chi 🥬", real: "Lil' Kim", gender: "FEMALE", style: "Hip-hop, raunchy lyrics, Brooklyn." },
  { key: "Foxy Brow-ny", label: "Foxy Brow-ny 🦊", real: "Foxy Brown", gender: "FEMALE", style: "Hip-hop, Brooklyn, Ill Na Na." },
  { key: "Trina-misu", label: "Trina-misu 🍰", real: "Trina", gender: "FEMALE", style: "Hip-hop, Miami, raunchy confident flow." },
  { key: "Remy Ma-ple", label: "Remy Ma-ple 🍁", real: "Remy Ma", gender: "FEMALE", style: "Hip-hop, Bronx, Terror Squad." },
  { key: "Da Brat-wurst", label: "Da Brat-wurst 🌭", real: "Da Brat", gender: "FEMALE", style: "Hip-hop, Chicago, So So Def, tomboy style." },
  { key: "Left Eye-blind", label: "Left Eye-blind 👁️", real: "Lisa Left Eye Lopes", gender: "FEMALE", style: "Hip-hop, TLC, rapping and singing, Atlanta." },
  { key: "Queen Lati-fah", label: "Queen Lati-fah ☕", real: "Queen Latifah", gender: "FEMALE", style: "Hip-hop, Newark, U.N.I.T.Y., jazz influences." },
  { key: "MC Lyte-ning", label: "MC Lyte-ning ⚡", real: "MC Lyte", gender: "FEMALE", style: "Hip-hop, Brooklyn, pioneering female MC." },
  { key: "Rox-anne Shanté", label: "Rox-anne Shanté 🎤", real: "Roxanne Shanté", gender: "FEMALE", style: "Hip-hop, Queensbridge, Roxanne's Revenge." },
  { key: "Monie Love-ly", label: "Monie Love-ly 💕", real: "Monie Love", gender: "FEMALE", style: "Hip-hop, British-American, Ladies First." },
  { key: "Yo-Yo-yo", label: "Yo-Yo-yo 🪀", real: "Yo-Yo", gender: "FEMALE", style: "Hip-hop, Compton, West Coast female MC." },
  { key: "Bahamadia-mond", label: "Bahamadia-mond 💎", real: "Bahamadia", gender: "FEMALE", style: "Hip-hop, Philadelphia, jazz-influenced lyricism." },
  { key: "Jean Grae-y", label: "Jean Grae-y 🎨", real: "Jean Grae", gender: "FEMALE", style: "Hip-hop, South Africa-born, NYC, complex lyricism." },
  { key: "Raps-ody", label: "Raps-ody 📖", real: "Rapsody", gender: "FEMALE", style: "Hip-hop, North Carolina, conscious lyricism." },
  { key: "Nona-me", label: "Nona-me 🎵", real: "Noname", gender: "FEMALE", style: "Hip-hop, Chicago, poetic jazz-influenced rap." },
  { key: "Little Simz-ter", label: "Little Simz-ter 👧", real: "Little Simz", gender: "FEMALE", style: "Hip-hop, London, introspective, Mercury Prize winner." },
  { key: "Stefflon Don-ut", label: "Stefflon Don-ut 🍩", real: "Stefflon Don", gender: "FEMALE", style: "Hip-hop, dancehall, British-Jamaican." },
  { key: "Ms. Dy-namite", label: "Ms. Dy-namite 💥", real: "Ms. Dynamite", gender: "FEMALE", style: "Hip-hop, UK garage, British." },
  { key: "Shystie-boots", label: "Shystie-boots 👢", real: "Shystie", gender: "FEMALE", style: "Hip-hop, grime, British." },
  { key: "Lady Les-hur", label: "Lady Les-hur 🎤", real: "Lady Leshurr", gender: "FEMALE", style: "Hip-hop, grime, Birmingham, Queen's Speech." },
  { key: "Ms. Banks-y", label: "Ms. Banks-y 🎨", real: "Ms. Banks", gender: "FEMALE", style: "Hip-hop, British-Nigerian, confident flow." },
  { key: "Iggy Azalea-nt", label: "Iggy Azalea-nt 🐜", real: "Iggy Azalea", gender: "FEMALE", style: "Hip-hop, Australian, Southern rap influence." },
  { key: "Cup-cakKe", label: "Cup-cakKe 🧁", real: "CupcakKe", gender: "FEMALE", style: "Hip-hop, Chicago, explicit comedy rap." },
  { key: "Saweetie-pie", label: "Saweetie-pie 🥧", real: "Saweetie", gender: "FEMALE", style: "Hip-hop, Bay Area, Icy Girl." },
  { key: "Coi Ler-ay", label: "Coi Ler-ay 🌈", real: "Coi Leray", gender: "FEMALE", style: "Hip-hop, New Jersey, melodic rap." },
  { key: "Flo Milli-on", label: "Flo Milli-on 💰", real: "Flo Milli", gender: "FEMALE", style: "Hip-hop, Alabama, confident, viral." },
  { key: "Latto-tto", label: "Latto-tto 🎰", real: "Latto", gender: "FEMALE", style: "Hip-hop, Atlanta, confident female rapper." },
  { key: "GloRilla-gorilla", label: "GloRilla-gorilla 🦍", real: "GloRilla", gender: "FEMALE", style: "Hip-hop, Memphis, aggressive flow." },
  { key: "Sexyy Red-velvet", label: "Sexyy Red-velvet 🍰", real: "Sexyy Red", gender: "FEMALE", style: "Hip-hop, St. Louis, raunchy confident." },
  { key: "Ice Spice-rack", label: "Ice Spice-rack 🌶️", real: "Ice Spice", gender: "FEMALE", style: "Hip-hop, Bronx, drill influence, Munch." },
  { key: "Doechii-tee", label: "Doechii-tee 🍵", real: "Doechii", gender: "FEMALE", style: "Hip-hop, Tampa, versatile flow." },
  { key: "Baby Tate-r-tot", label: "Baby Tate-r-tot 🥔", real: "Baby Tate", gender: "FEMALE", style: "Hip-hop, Atlanta, playful confident." },
  { key: "Rubi Rose-bud", label: "Rubi Rose-bud 🌹", real: "Rubi Rose", gender: "FEMALE", style: "Hip-hop, Kentucky, model rapper." },
  { key: "Asian Doll-ar", label: "Asian Doll-ar 💵", real: "Asian Doll", gender: "FEMALE", style: "Hip-hop, Dallas, aggressive drill." },
  { key: "Rocky Badd-ie", label: "Rocky Badd-ie 👿", real: "Rocky Badd", gender: "FEMALE", style: "Hip-hop, Detroit, battle rap." },
  { key: "Kash Doll-ar", label: "Kash Doll-ar 💵", real: "Kash Doll", gender: "FEMALE", style: "Hip-hop, Detroit, confident female rapper." },
  { key: "DeJ Loaf-er", label: "DeJ Loaf-er 🍞", real: "DeJ Loaf", gender: "FEMALE", style: "Hip-hop, Detroit, melodic rap." },
  { key: "Tierra Whack-amole", label: "Tierra Whack-amole 🥑", real: "Tierra Whack", gender: "FEMALE", style: "Hip-hop, Philadelphia, experimental, Whack World." },
  { key: "Rico Nas-ty", label: "Rico Nas-ty 🤢", real: "Rico Nasty", gender: "FEMALE", style: "Hip-hop, Maryland, punk rap, aggressive." },
  { key: "Tokis-cha", label: "Tokis-cha 🍫", real: "Tokischa", gender: "FEMALE", style: "Dembow, Dominican, provocative reggaeton." },
  { key: "Young M.A.-n", label: "Young M.A.-n 👩", real: "Young M.A", gender: "FEMALE", style: "Hip-hop, Brooklyn, masculine-presenting female rapper." },
  { key: "Leikeli47-eleven", label: "Leikeli47-eleven 🏪", real: "Leikeli47", gender: "FEMALE", style: "Hip-hop, Brooklyn, masked rapper, versatile." },
  { key: "Chika-chu", label: "Chika-chu ⚡", real: "CHIKA", gender: "FEMALE", style: "Hip-hop, Alabama, socially conscious, Warner Bros." },
  { key: "Sa-Roc-ket", label: "Sa-Roc-ket 🚀", real: "Sa-Roc", gender: "FEMALE", style: "Hip-hop, Atlanta, conscious lyricism, Rhymesayers." },
  { key: "NoName-call-ing", label: "NoName-call-ing 📞", real: "Noname", gender: "FEMALE", style: "Hip-hop, Chicago, poetic jazz-influenced rap." },
];

export const RANDOM_ARTISTS = ARTISTS.map(a => a.key);

export const VISUALIZER_STYLES = [
  { id: 'bars', name: 'Classic Bars' },
  { id: 'waveform', name: 'Oscilloscope' },
  { id: 'circle-bars', name: 'Radial Bars' },
  { id: 'circle-wave', name: 'Radial Wave' },
  { id: 'starburst', name: 'Starburst' },
  { id: 'matrix', name: 'Digital Rain' },
  { id: 'particles', name: 'Particle Swarm' },
  { id: 'neon-grid', name: 'Synthwave Grid' },
  { id: 'hypnotic-rings', name: 'Hypno Rings' },
  { id: 'frequency-blocks', name: 'Freq Blocks' },
  { id: 'afterimage-spiral', name: '🔮 Spiral Afterimage' },
  { id: 'negative-flash', name: '👁️ Negative Flash' },
  { id: 'flicker-grid', name: '✨ Flicker Grid' },
  { id: 'color-warp', name: '🌈 Color Warp' },
  { id: 'peripheral-drift', name: '🌀 Peripheral Drift' },
  { id: 'kaleidoscope', name: 'Kaleidoscope' },
  { id: 'retro-sun', name: 'Outrun Sun' },
  { id: 'laser-show', name: 'Laser Show' },
  { id: 'pulsing-orbs', name: 'Pulsing Orbs' },
  { id: 'cyberpunk-city', name: 'Night City' },
  { id: 'equalizer-grid', name: 'EQ Grid' },
  { id: 'sound-tunnels', name: 'Warp Tunnel' },
  { id: 'liquid', name: 'Liquid Audio' },
  { id: 'glitch', name: 'Glitch Core' },
  { id: 'fractal', name: 'Audio Fractal' },
  { id: 'neon-horizon', name: 'Neon Horizon' },
  { id: 'fractal-bloom', name: 'Fractal Bloom' },
  { id: 'aurora-borealis', name: 'Aurora Borealis' },
  { id: 'cosmic-pulse', name: 'Cosmic Pulse' },
  { id: 'kinetic-waves', name: 'Kinetic Waves' },
  { id: 'cyber-circuit', name: 'Cyber Circuit' },
  { id: 'geometric-shift', name: 'Geometric Shift' },
  { id: 'stardust-blast', name: 'Stardust Blast' },
  { id: 'prism-vortex', name: 'Prism Vortex' },
  { id: 'liquid-gold', name: 'Liquid Gold' }
];

export const SKINS = {
  winamp: {
    name: 'Winamp 2.0',
    bg: 'bg-[#111]',
    window: 'bg-[#272736] border-t-2 border-l-2 border-[#4a4a68] border-b-2 border-r-2 border-[#14141d] shadow-2xl',
    titleBar: 'bg-gradient-to-r from-[#1a1a2e] to-[#2a2a4a] text-[#8b8b99] border border-[#111]',
    lcd: 'bg-[#0a0a0a] border-t-2 border-l-2 border-[#000] border-b-2 border-r-2 border-[#333] text-[#00ff00]',
    lcdFont: 'font-[family-name:var(--font-vt323)]',
    button: 'bg-[#c0c0c0] border-t-2 border-l-2 border-[#fff] border-b-2 border-r-2 border-[#555] text-black active:border-t-[#555] active:border-l-[#555] active:border-b-[#fff] active:border-r-[#fff]',
    panel: 'bg-[#3a3a52] border-t-2 border-l-2 border-[#5a5a7a] border-b-2 border-r-2 border-[#1a1a2a]',
    input: 'bg-black text-[#00ff00] border-2 border-[#555] focus:border-[#00ff00]',
    text: 'text-[#00aa00]',
    highlight: 'bg-[#005500] text-[#00ff00]',
    hover: 'hover:bg-[#003300]'
  },
  wmp: {
    name: 'Windows Media 7',
    bg: 'bg-[#d4d0c8]',
    window: 'bg-[#e4e4e4] border-2 border-[#ffffff] border-b-[#808080] border-r-[#808080] rounded-lg shadow-xl',
    titleBar: 'bg-gradient-to-r from-[#0055e5] to-[#2288ff] text-white rounded-t-md',
    lcd: 'bg-[#000044] border-2 border-[#808080] border-b-[#ffffff] border-r-[#ffffff] text-[#00aaff] rounded-md',
    lcdFont: 'font-sans font-bold',
    button: 'bg-[#e4e4e4] border-2 border-[#ffffff] border-b-[#808080] border-r-[#808080] text-black rounded-full active:border-t-[#808080] active:border-l-[#808080] active:border-b-[#ffffff] active:border-r-[#ffffff]',
    panel: 'bg-[#d4d0c8] border-2 border-[#ffffff] border-b-[#808080] border-r-[#808080] rounded-md',
    input: 'bg-white text-black border-2 border-[#808080] border-b-[#ffffff] border-r-[#ffffff] focus:border-[#0055e5]',
    text: 'text-black',
    highlight: 'bg-[#0055e5] text-white',
    hover: 'hover:bg-[#c0c0c0]'
  },
  realplayer: {
    name: 'RealPlayer G2',
    bg: 'bg-[#a0a0a0]',
    window: 'bg-[#cccccc] border-2 border-[#ffffff] border-b-[#666666] border-r-[#666666] shadow-md',
    titleBar: 'bg-[#000080] text-white',
    lcd: 'bg-[#000000] border-2 border-[#666666] border-b-[#ffffff] border-r-[#ffffff] text-[#ff0000]',
    lcdFont: 'font-mono font-bold',
    button: 'bg-[#cccccc] border-2 border-[#ffffff] border-b-[#666666] border-r-[#666666] text-black active:border-t-[#666666] active:border-l-[#666666] active:border-b-[#ffffff] active:border-r-[#ffffff]',
    panel: 'bg-[#b0b0b0] border-2 border-[#ffffff] border-b-[#666666] border-r-[#666666]',
    input: 'bg-white text-black border-2 border-[#666666] border-b-[#ffffff] border-r-[#ffffff] focus:border-[#000080]',
    text: 'text-black',
    highlight: 'bg-[#000080] text-white',
    hover: 'hover:bg-[#a0a0a0]'
  },
  itunes: {
    name: 'iTunes 4 (Metal)',
    bg: 'bg-[#e0e0e0]',
    window: 'bg-gradient-to-b from-[#e8e8e8] to-[#b0b0b0] border border-[#999999] rounded-lg shadow-lg',
    titleBar: 'bg-transparent text-black text-center border-b border-[#999999]',
    lcd: 'bg-[#d4ebd4] border border-[#88a088] text-[#000000] rounded-sm',
    lcdFont: 'font-sans',
    button: 'bg-gradient-to-b from-[#ffffff] to-[#cccccc] border border-[#999999] text-black rounded-full active:from-[#cccccc] active:to-[#999999]',
    panel: 'bg-transparent border-t border-[#ffffff]',
    input: 'bg-white text-black border border-[#999999] rounded-full px-3 focus:border-[#55aaff]',
    text: 'text-black',
    highlight: 'bg-[#55aaff] text-white',
    hover: 'hover:bg-[#d0d0d0]'
  },
  quicktime: {
    name: 'QuickTime 7',
    bg: 'bg-[#000000]',
    window: 'bg-gradient-to-b from-[#444444] to-[#222222] border border-[#111111] rounded-xl shadow-2xl',
    titleBar: 'bg-transparent text-[#cccccc] text-center',
    lcd: 'bg-[#000000] border border-[#111111] text-[#ffffff]',
    lcdFont: 'font-sans',
    button: 'bg-gradient-to-b from-[#555555] to-[#333333] border border-[#111111] text-white rounded-full active:from-[#333333] active:to-[#111111]',
    panel: 'bg-transparent',
    input: 'bg-[#111111] text-white border border-[#000000] rounded-full px-3 focus:border-[#555555]',
    text: 'text-[#cccccc]',
    highlight: 'bg-[#555555] text-white',
    hover: 'hover:bg-[#333333]'
  },
  mpc: {
    name: 'Media Player Classic',
    bg: 'bg-[#1e1e1e]',
    window: 'bg-[#2d2d30] border border-[#3f3f46] shadow-2xl',
    titleBar: 'bg-[#3e3e42] text-[#cccccc] px-2 py-1',
    lcd: 'bg-[#1e1e1e] border border-[#3f3f46] text-[#cccccc]',
    lcdFont: 'font-sans',
    button: 'bg-[#3e3e42] hover:bg-[#505050] text-[#cccccc] border border-[#555555]',
    panel: 'bg-[#2d2d30]',
    input: 'bg-[#1e1e1e] text-[#cccccc] border border-[#3f3f46]',
    text: 'text-[#cccccc]',
    highlight: 'bg-[#3f3f46] text-white',
    hover: 'hover:bg-[#505050]'
  },
  vlc: {
    name: 'TrafficCone Player',
    bg: 'bg-[#ff8c00]',
    window: 'bg-[#ffffff] border-4 border-[#ff8c00] shadow-xl',
    titleBar: 'bg-[#ff8c00] text-white font-bold px-2 py-1',
    lcd: 'bg-gray-100 border border-gray-300 text-black',
    lcdFont: 'font-sans',
    button: 'bg-[#ff8c00] hover:bg-[#e67e00] text-white font-bold',
    panel: 'bg-[#ffffff]',
    input: 'bg-gray-100 text-black border border-gray-300',
    text: 'text-black',
    highlight: 'bg-[#ff8c00] text-white',
    hover: 'hover:bg-[#e67e00]'
  },
  foobar: {
    name: 'FUBAR2000',
    bg: 'bg-[#ffffff]',
    window: 'bg-[#ffffff] border border-[#a0a0a0] shadow-sm',
    titleBar: 'bg-[#f0f0f0] text-black border-b border-[#a0a0a0] px-2 py-1',
    lcd: 'bg-white border border-[#a0a0a0] text-black',
    lcdFont: 'font-mono',
    button: 'bg-[#f0f0f0] hover:bg-[#e0e0e0] text-black border border-[#a0a0a0]',
    panel: 'bg-[#ffffff]',
    input: 'bg-white text-black border border-[#a0a0a0]',
    text: 'text-black',
    highlight: 'bg-[#e0e0e0] text-black',
    hover: 'hover:bg-[#f0f0f0]'
  },
  macamp: {
    name: 'MacAmp',
    bg: 'bg-[#e0e0e0]',
    window: 'bg-[#f5f5f5] border border-[#cccccc] rounded-lg shadow-lg',
    titleBar: 'bg-gradient-to-b from-[#ffffff] to-[#e0e0e0] text-black rounded-t-lg border-b border-[#cccccc]',
    lcd: 'bg-white border border-[#cccccc] text-black',
    lcdFont: 'font-sans',
    button: 'bg-gradient-to-b from-[#ffffff] to-[#e0e0e0] hover:from-[#e0e0e0] hover:to-[#cccccc] text-black border border-[#cccccc] rounded',
    panel: 'bg-[#f5f5f5]',
    input: 'bg-white text-black border border-[#cccccc] rounded',
    text: 'text-black',
    highlight: 'bg-[#e0e0e0] text-black',
    hover: 'hover:bg-[#cccccc]'
  },
  linuxamp: {
    name: 'LinuxAmp',
    bg: 'bg-[#300a24]',
    window: 'bg-[#2c001e] border border-[#dd4814]',
    titleBar: 'bg-[#dd4814] text-white',
    lcd: 'bg-[#300a24] border border-[#dd4814] text-white',
    lcdFont: 'font-mono',
    button: 'bg-[#dd4814] hover:bg-[#e95420] text-white',
    panel: 'bg-[#2c001e]',
    input: 'bg-[#300a24] text-white border border-[#dd4814]',
    text: 'text-white',
    highlight: 'bg-[#dd4814] text-white',
    hover: 'hover:bg-[#e95420]'
  },
  spotify: {
    name: 'Spotify Dark',
    bg: 'bg-[#121212]',
    window: 'bg-[#181818] border border-[#282828] rounded-lg shadow-2xl',
    titleBar: 'bg-[#181818] text-[#fff] rounded-t-lg border-b border-[#282828]',
    lcd: 'bg-[#282828] text-[#1db954] rounded-md',
    lcdFont: 'font-sans font-bold',
    button: 'bg-[#1db954] text-black rounded-full hover:scale-105 transition-transform border-none font-bold',
    panel: 'bg-[#121212] rounded-md',
    input: 'bg-[#282828] text-white border border-transparent focus:border-[#1db954] rounded-sm hover:bg-[#333]',
    text: 'text-[#b3b3b3]',
    highlight: 'bg-[#1db954] text-black',
    hover: 'hover:bg-[#282828] hover:text-white'
  },
  synthwave: {
    name: 'Synthwave 84',
    bg: 'bg-[#2b213a]',
    window: 'bg-[#241b2f] border-2 border-[#ff2a6d] shadow-[0_0_15px_#ff2a6d]',
    titleBar: 'bg-gradient-to-r from-[#05d9e8] to-[#0182cb] text-white border-b-2 border-[#ff2a6d]',
    lcd: 'bg-[#000] text-[#05d9e8] border-2 border-[#0182cb] shadow-[inset_0_0_10px_#05d9e8]',
    lcdFont: 'font-[family-name:var(--font-vt323)]',
    button: 'bg-[#ff2a6d] text-white border-2 border-[#ff2a6d] hover:bg-[#05d9e8] hover:border-[#05d9e8] hover:shadow-[0_0_10px_#05d9e8] transition-all',
    panel: 'bg-[#261447] border border-[#0182cb]',
    input: 'bg-[#000] text-[#ff2a6d] border border-[#05d9e8] focus:shadow-[0_0_10px_#ff2a6d]',
    text: 'text-[#05d9e8]',
    highlight: 'bg-[#ff2a6d] text-white',
    hover: 'hover:bg-[#3a2a4a]'
  },
  cyberpunk: {
    name: 'Cyberpunk 2077',
    bg: 'bg-[#fcee0a]',
    window: 'bg-[#000] border-4 border-[#00f0ff] clip-path-polygon-[0_0,100%_0,100%_calc(100%-20px),calc(100%-20px)_100%,0_100%]',
    titleBar: 'bg-[#fcee0a] text-black font-bold uppercase tracking-widest',
    lcd: 'bg-[#000] text-[#ff003c] border border-[#00f0ff]',
    lcdFont: 'font-mono font-bold',
    button: 'bg-[#00f0ff] text-black font-bold uppercase hover:bg-[#ff003c] hover:text-white transition-colors',
    panel: 'bg-[#111] border border-[#333]',
    input: 'bg-[#000] text-[#00f0ff] border-b-2 border-[#fcee0a] focus:border-[#ff003c]',
    text: 'text-[#00f0ff]',
    highlight: 'bg-[#ff003c] text-white',
    hover: 'hover:bg-[#222]'
  },
  vaporwave: {
    name: 'Vaporwave',
    bg: 'bg-[#ffb3ba]',
    window: 'bg-[#bae1ff] border-4 border-[#baffc9] shadow-[10px_10px_0px_#ffb3ba]',
    titleBar: 'bg-gradient-to-r from-[#ffdfba] to-[#ffffba] text-[#ffb3ba] font-serif italic text-lg',
    lcd: 'bg-[#fff] text-[#bae1ff] border-2 border-[#ffb3ba]',
    lcdFont: 'font-serif italic',
    button: 'bg-[#baffc9] text-[#ffb3ba] border-2 border-[#fff] hover:bg-[#ffffba] transition-colors',
    panel: 'bg-[#ffdfba] border-2 border-[#fff]',
    input: 'bg-[#fff] text-[#ffb3ba] border-2 border-[#bae1ff] focus:border-[#baffc9]',
    text: 'text-[#ffb3ba]',
    highlight: 'bg-[#bae1ff] text-white',
    hover: 'hover:bg-[#ffffba]'
  },
  matrix: {
    name: 'The Matrix',
    bg: 'bg-[#000]',
    window: 'bg-[#000] border-2 border-[#0f0] shadow-[0_0_20px_#0f0]',
    titleBar: 'bg-[#000] text-[#0f0] border-b-2 border-[#0f0] font-mono',
    lcd: 'bg-[#000] text-[#0f0] border border-[#0f0]',
    lcdFont: 'font-mono',
    button: 'bg-[#000] text-[#0f0] border border-[#0f0] hover:bg-[#0f0] hover:text-black transition-colors',
    panel: 'bg-[#000] border border-[#0f0]',
    input: 'bg-[#000] text-[#0f0] border-b border-[#0f0] focus:shadow-[0_0_10px_#0f0]',
    text: 'text-[#0f0]',
    highlight: 'bg-[#0f0] text-black',
    hover: 'hover:bg-[#0a0]'
  },
  gameboy: {
    name: 'Gameboy',
    bg: 'bg-[#c4cfa1]',
    window: 'bg-[#e0e0e0] border-4 border-[#8b8b8b] rounded-b-3xl shadow-xl',
    titleBar: 'bg-[#8b8b8b] text-white rounded-t-sm font-bold uppercase',
    lcd: 'bg-[#8bac0f] text-[#0f380f] border-4 border-[#306230] rounded-sm shadow-[inset_0_0_10px_rgba(0,0,0,0.5)]',
    lcdFont: 'font-[family-name:var(--font-vt323)]',
    button: 'bg-[#980044] text-white rounded-full w-8 h-8 flex items-center justify-center shadow-[2px_2px_0px_#550022] active:shadow-none active:translate-y-[2px]',
    panel: 'bg-[#d0d0d0] border-2 border-[#a0a0a0] rounded-md',
    input: 'bg-[#8bac0f] text-[#0f380f] border-2 border-[#306230] focus:border-[#0f380f]',
    text: 'text-[#333]',
    highlight: 'bg-[#306230] text-[#8bac0f]',
    hover: 'hover:bg-[#c0c0c0]'
  },
  macos9: {
    name: 'Mac OS 9',
    bg: 'bg-[#5555aa]',
    window: 'bg-[#dddddd] border border-[#000] shadow-[2px_2px_0px_#000]',
    titleBar: 'bg-gradient-to-b from-[#ffffff] to-[#cccccc] text-black border-b border-[#000] text-center font-bold flex justify-center items-center',
    lcd: 'bg-[#ffffff] text-black border border-[#888888] shadow-inner',
    lcdFont: 'font-sans',
    button: 'bg-gradient-to-b from-[#ffffff] to-[#dddddd] border border-[#888888] text-black rounded-sm active:from-[#cccccc] active:to-[#aaaaaa]',
    panel: 'bg-[#eeeeee] border border-[#bbbbbb]',
    input: 'bg-white text-black border border-[#888888] focus:border-[#0000ff]',
    text: 'text-black',
    highlight: 'bg-[#0000aa] text-white',
    hover: 'hover:bg-[#cccccc]'
  },
  hacker: {
    name: 'Hacker Terminal',
    bg: 'bg-[#000]',
    window: 'bg-[#000] border border-[#33ff00]',
    titleBar: 'bg-[#000] text-[#33ff00] border-b border-[#33ff00] font-mono',
    lcd: 'bg-[#000] text-[#33ff00]',
    lcdFont: 'font-mono',
    button: 'bg-[#000] text-[#33ff00] border border-[#33ff00] hover:bg-[#33ff00] hover:text-[#000]',
    panel: 'bg-[#000]',
    input: 'bg-[#000] text-[#33ff00] border-b border-[#33ff00] focus:outline-none',
    text: 'text-[#33ff00]',
    highlight: 'bg-[#33ff00] text-[#000]',
    hover: 'hover:bg-[#111]'
  },
  zune: {
    name: 'Zune',
    bg: 'bg-[#3e2723]',
    window: 'bg-[#212121] border border-[#4e342e] rounded-lg shadow-2xl',
    titleBar: 'bg-[#ff6f00] text-white rounded-t-lg font-sans font-light text-lg px-4',
    lcd: 'bg-[#000000] text-[#ff6f00] border-none',
    lcdFont: 'font-sans font-light text-2xl',
    button: 'bg-transparent text-[#ff6f00] border border-[#ff6f00] rounded-full hover:bg-[#ff6f00] hover:text-white transition-colors',
    panel: 'bg-[#303030] rounded-md',
    input: 'bg-[#424242] text-white border-none focus:ring-1 focus:ring-[#ff6f00] rounded-sm',
    text: 'text-[#e0e0e0]',
    highlight: 'bg-[#ff6f00] text-white',
    hover: 'hover:bg-[#424242]'
  },
  win95: {
    name: 'Windows 95',
    bg: 'bg-[#008080]',
    window: 'bg-[#c0c0c0] border-t-2 border-l-2 border-[#fff] border-b-2 border-r-2 border-[#808080] shadow-[2px_2px_0px_#000]',
    titleBar: 'bg-[#000080] text-white font-bold px-1 flex items-center',
    lcd: 'bg-[#fff] text-black border-t-2 border-l-2 border-[#808080] border-b-2 border-r-2 border-[#fff]',
    lcdFont: 'font-sans',
    button: 'bg-[#c0c0c0] border-t-2 border-l-2 border-[#fff] border-b-2 border-r-2 border-[#808080] text-black active:border-t-[#808080] active:border-l-[#808080] active:border-b-[#fff] active:border-r-[#fff]',
    panel: 'bg-[#c0c0c0]',
    input: 'bg-[#fff] text-black border-t-2 border-l-2 border-[#808080] border-b-2 border-r-2 border-[#fff] focus:outline-none',
    text: 'text-black',
    highlight: 'bg-[#000080] text-white',
    hover: 'hover:bg-[#d4d0c8]'
  },
  winxp: {
    name: 'Windows XP',
    bg: 'bg-[#245edb]',
    window: 'bg-[#ece9d8] border border-[#0055ea] rounded-t-xl shadow-xl',
    titleBar: 'bg-gradient-to-b from-[#0058e6] via-[#3a93ff] to-[#003fbd] text-white rounded-t-lg font-bold px-3 py-1 text-shadow-sm',
    lcd: 'bg-white text-black border border-[#7f9db9]',
    lcdFont: 'font-sans',
    button: 'bg-gradient-to-b from-[#f4f3ee] to-[#d4d0c8] border border-[#fff] border-b-[#888] border-r-[#888] text-black rounded-sm hover:from-[#fff] hover:to-[#e0dfd9] active:from-[#d4d0c8] active:to-[#f4f3ee]',
    panel: 'bg-gradient-to-b from-[#ffffff] to-[#ece9d8] border border-[#7f9db9] rounded-sm',
    input: 'bg-white text-black border border-[#7f9db9] focus:border-[#0058e6]',
    text: 'text-black',
    highlight: 'bg-[#316ac5] text-white',
    hover: 'hover:bg-[#e0dfd9]'
  },
  amiga: {
    name: 'Amiga Workbench',
    bg: 'bg-[#0055aa]',
    window: 'bg-[#aaaaaa] border-2 border-[#ffffff] border-b-[#000000] border-r-[#000000]',
    titleBar: 'bg-[#ffffff] text-[#0055aa] font-bold px-2 border-b-2 border-[#000000]',
    lcd: 'bg-[#0055aa] text-[#ffffff] border-2 border-[#000000] border-b-[#ffffff] border-r-[#ffffff]',
    lcdFont: 'font-mono',
    button: 'bg-[#aaaaaa] text-[#000000] border-2 border-[#ffffff] border-b-[#000000] border-r-[#000000] active:border-[#000000] active:border-b-[#ffffff] active:border-r-[#ffffff]',
    panel: 'bg-[#aaaaaa]',
    input: 'bg-[#ffffff] text-[#000000] border-2 border-[#000000] border-b-[#ffffff] border-r-[#ffffff]',
    text: 'text-[#000000]',
    highlight: 'bg-[#ff8800] text-[#000000]',
    hover: 'hover:bg-[#cccccc]'
  },
  c64: {
    name: 'Commodore 64',
    bg: 'bg-[#352879]',
    window: 'bg-[#6c5eb5] border-4 border-[#352879]',
    titleBar: 'bg-[#352879] text-[#6c5eb5] font-mono font-bold text-center',
    lcd: 'bg-[#352879] text-[#6c5eb5] border-2 border-[#6c5eb5]',
    lcdFont: 'font-mono uppercase',
    button: 'bg-[#352879] text-[#6c5eb5] border-2 border-[#6c5eb5] hover:bg-[#6c5eb5] hover:text-[#352879]',
    panel: 'bg-[#6c5eb5]',
    input: 'bg-[#352879] text-[#6c5eb5] border-2 border-[#6c5eb5] focus:outline-none',
    text: 'text-[#352879]',
    highlight: 'bg-[#352879] text-[#6c5eb5]',
    hover: 'hover:bg-[#8b7cd6]'
  },
  dos: {
    name: 'MS-DOS',
    bg: 'bg-[#000]',
    window: 'bg-[#000] border-2 border-[#aaa]',
    titleBar: 'bg-[#aaa] text-[#000] font-mono font-bold text-center',
    lcd: 'bg-[#000] text-[#aaa] border border-[#aaa]',
    lcdFont: 'font-mono',
    button: 'bg-[#000] text-[#aaa] border border-[#aaa] hover:bg-[#aaa] hover:text-[#000]',
    panel: 'bg-[#000]',
    input: 'bg-[#000] text-[#aaa] border-b border-[#aaa] focus:outline-none',
    text: 'text-[#aaa]',
    highlight: 'bg-[#aaa] text-[#000]',
    hover: 'hover:bg-[#222]'
  },
  frutiger: {
    name: 'Frutiger Aero',
    bg: 'bg-gradient-to-br from-[#87ceeb] to-[#e0f6ff]',
    window: 'bg-white/60 backdrop-blur-md border border-white/80 rounded-2xl shadow-[0_8px_32px_rgba(0,150,255,0.2)]',
    titleBar: 'bg-gradient-to-r from-[#4facfe] to-[#00f2fe] text-white rounded-t-2xl font-sans font-bold px-4 py-2 shadow-sm',
    lcd: 'bg-white/80 text-[#005c97] rounded-xl shadow-inner border border-white',
    lcdFont: 'font-sans text-lg',
    button: 'bg-gradient-to-b from-white to-[#e0f6ff] text-[#005c97] rounded-full shadow-md border border-white hover:shadow-lg hover:scale-105 transition-all',
    panel: 'bg-white/40 rounded-xl border border-white/50',
    input: 'bg-white/80 text-[#005c97] border border-[#87ceeb] rounded-full focus:ring-2 focus:ring-[#00f2fe]',
    text: 'text-[#005c97]',
    highlight: 'bg-[#00f2fe] text-white',
    hover: 'hover:bg-white/80'
  },
  y2k: {
    name: 'Y2K Metallic',
    bg: 'bg-[#c0c0c0]',
    window: 'bg-gradient-to-br from-[#ffffff] via-[#dcdcdc] to-[#999999] border-2 border-[#fff] rounded-3xl shadow-[0_10px_20px_rgba(0,0,0,0.3)]',
    titleBar: 'bg-gradient-to-r from-[#ff6600] to-[#ff9900] text-white rounded-t-3xl font-black italic tracking-tighter px-4 py-1 border-b-2 border-[#fff]',
    lcd: 'bg-[#0033ff] text-[#00ffff] rounded-2xl border-4 border-[#fff] shadow-[inset_0_0_15px_#000]',
    lcdFont: 'font-mono font-bold italic',
    button: 'bg-gradient-to-b from-[#fff] to-[#ccc] text-[#0033ff] rounded-full border-2 border-[#fff] shadow-md hover:from-[#e6f2ff] hover:to-[#99ccff] font-black italic',
    panel: 'bg-gradient-to-br from-[#e6e6e6] to-[#cccccc] rounded-2xl border border-[#fff]',
    input: 'bg-[#fff] text-[#0033ff] border-2 border-[#0033ff] rounded-full focus:ring-2 focus:ring-[#ff6600]',
    text: 'text-[#0033ff]',
    highlight: 'bg-[#ff6600] text-white',
    hover: 'hover:bg-[#ffffff]'
  },
  geocities: {
    name: 'GeoCities',
    bg: 'bg-[#000000] bg-[url("https://www.transparenttextures.com/patterns/stardust.png")]',
    window: 'bg-[#000080] border-4 border-[#ffff00] border-dashed',
    titleBar: 'bg-[#ff0000] text-[#ffff00] font-comic font-bold text-center underline',
    lcd: 'bg-[#000000] text-[#00ff00] border-2 border-[#ff00ff]',
    lcdFont: 'font-comic',
    button: 'bg-[#00ffff] text-[#ff0000] border-4 border-[outset] border-[#00ffff] font-bold hover:bg-[#ff00ff] hover:text-[#ffff00]',
    panel: 'bg-[#008000] border-2 border-[#ffff00] border-dotted',
    input: 'bg-[#ffffff] text-[#000000] border-2 border-[#ff0000]',
    text: 'text-[#ffff00]',
    highlight: 'bg-[#ff00ff] text-[#ffffff]',
    hover: 'hover:bg-[#0000ff]'
  },
  ubuntu: {
    name: 'Ubuntu (Ambiance)',
    bg: 'bg-[#2c001e]',
    window: 'bg-[#3c3b37] border border-[#222] rounded-lg shadow-2xl',
    titleBar: 'bg-gradient-to-b from-[#53514a] to-[#3c3b37] text-[#dfdbd2] rounded-t-lg px-2 py-1 flex justify-between items-center',
    lcd: 'bg-[#222] text-[#dd4814] rounded shadow-inner border border-[#111]',
    lcdFont: 'font-ubuntu',
    button: 'bg-gradient-to-b from-[#555] to-[#333] border border-[#222] text-[#dfdbd2] rounded-full hover:from-[#666] hover:to-[#444]',
    panel: 'bg-[#333] rounded-md border border-[#222]',
    input: 'bg-[#fff] text-[#333] border border-[#dd4814] rounded focus:ring-1 focus:ring-[#dd4814]',
    text: 'text-[#dfdbd2]',
    highlight: 'bg-[#dd4814] text-white',
    hover: 'hover:bg-[#444]'
  },
  beos: {
    name: 'BeOS',
    bg: 'bg-[#232323]',
    window: 'bg-[#d4d0c8] border-2 border-[#fff] border-b-[#808080] border-r-[#808080] shadow-lg',
    titleBar: 'bg-[#d4a017] text-black font-bold px-2 py-1 flex items-center',
    lcd: 'bg-[#fff] text-[#d4a017] border border-[#808080]',
    lcdFont: 'font-sans font-bold',
    button: 'bg-[#d4d0c8] border-2 border-[#fff] border-b-[#808080] border-r-[#808080] text-black active:border-t-[#808080] active:border-l-[#808080] active:border-b-[#fff] active:border-r-[#fff]',
    panel: 'bg-[#d4d0c8] border border-[#808080]',
    input: 'bg-white text-black border border-[#808080] focus:border-[#d4a017]',
    text: 'text-black',
    highlight: 'bg-[#d4a017] text-black',
    hover: 'hover:bg-[#c0c0c0]'
  },
  os2: {
    name: 'OS/2 Warp',
    bg: 'bg-[#000080]',
    window: 'bg-[#c0c0c0] border-2 border-[#fff] border-b-[#404040] border-r-[#404040]',
    titleBar: 'bg-[#000080] text-white font-bold px-2 border-b-2 border-[#404040]',
    lcd: 'bg-[#000040] text-[#00ffff] border-2 border-[#404040] border-b-[#fff] border-r-[#fff]',
    lcdFont: 'font-mono',
    button: 'bg-[#c0c0c0] border-2 border-[#fff] border-b-[#404040] border-r-[#404040] text-black active:border-t-[#404040] active:border-l-[#404040] active:border-b-[#fff] active:border-r-[#fff]',
    panel: 'bg-[#c0c0c0]',
    input: 'bg-white text-black border-2 border-[#404040] border-b-[#fff] border-r-[#fff] focus:border-[#000080]',
    text: 'text-black',
    highlight: 'bg-[#000080] text-white',
    hover: 'hover:bg-[#d4d0c8]'
  },
  nextstep: {
    name: 'NeXTSTEP',
    bg: 'bg-[#2a2a2a]',
    window: 'bg-[#e0e0e0] border border-[#888] shadow-md',
    titleBar: 'bg-[#4a4a4a] text-white font-bold px-2 py-1 border-b border-[#888]',
    lcd: 'bg-[#1a1a1a] text-[#ff6600] border border-[#888]',
    lcdFont: 'font-serif',
    button: 'bg-[#e0e0e0] border border-[#888] text-black hover:bg-[#ff6600] hover:text-white',
    panel: 'bg-[#d0d0d0] border border-[#888]',
    input: 'bg-white text-black border border-[#888] focus:border-[#ff6600]',
    text: 'text-black',
    highlight: 'bg-[#ff6600] text-white',
    hover: 'hover:bg-[#c0c0c0]'
  },
  palm: {
    name: 'Palm OS',
    bg: 'bg-[#f5f0e1]',
    window: 'bg-[#f5f0e1] border-2 border-[#d4c4a8] rounded-sm shadow-sm',
    titleBar: 'bg-[#d4c4a8] text-[#4a3728] font-bold px-2 py-1 border-b border-[#b0a080]',
    lcd: 'bg-[#e8dcc0] text-[#4a3728] border border-[#b0a080]',
    lcdFont: 'font-sans',
    button: 'bg-[#d4c4a8] text-[#4a3728] border border-[#b0a080] rounded-sm hover:bg-[#c4b498]',
    panel: 'bg-[#ebe5d5] border border-[#d4c4a8]',
    input: 'bg-white text-[#4a3728] border border-[#b0a080] focus:border-[#8b6914]',
    text: 'text-[#4a3728]',
    highlight: 'bg-[#8b6914] text-white',
    hover: 'hover:bg-[#dcd0b8]'
  },
  ps2: {
    name: 'PlayStation 2',
    bg: 'bg-[#000033]',
    window: 'bg-[#000011] border-2 border-[#0066cc] shadow-[0_0_20px_#0066cc]',
    titleBar: 'bg-[#0066cc] text-white font-bold uppercase tracking-widest px-3 py-1',
    lcd: 'bg-[#000033] text-[#00ccff] border border-[#0066cc]',
    lcdFont: 'font-sans font-bold',
    button: 'bg-[#0066cc] text-white border border-[#00ccff] hover:bg-[#00ccff] hover:text-[#000033]',
    panel: 'bg-[#000022] border border-[#0066cc]',
    input: 'bg-[#000033] text-[#00ccff] border border-[#0066cc] focus:border-[#00ccff]',
    text: 'text-[#00ccff]',
    highlight: 'bg-[#0066cc] text-white',
    hover: 'hover:bg-[#000044]'
  },
  xbox: {
    name: 'Xbox Original',
    bg: 'bg-[#0e3b0e]',
    window: 'bg-[#000000] border-4 border-[#9bcf00] shadow-[0_0_15px_#9bcf00]',
    titleBar: 'bg-[#9bcf00] text-black font-black uppercase px-3 py-1',
    lcd: 'bg-[#000000] text-[#9bcf00] border-2 border-[#9bcf00]',
    lcdFont: 'font-mono font-bold',
    button: 'bg-[#9bcf00] text-black font-bold uppercase hover:bg-[#b8e600]',
    panel: 'bg-[#0a0a0a] border border-[#1a1a1a]',
    input: 'bg-[#000000] text-[#9bcf00] border-2 border-[#9bcf00] focus:border-[#b8e600]',
    text: 'text-[#9bcf00]',
    highlight: 'bg-[#9bcf00] text-black',
    hover: 'hover:bg-[#1a1a1a]'
  },
  dreamcast: {
    name: 'Dreamcast',
    bg: 'bg-[#ff6600]',
    window: 'bg-[#ffffff] border-4 border-[#ff6600] shadow-xl',
    titleBar: 'bg-[#ff6600] text-white font-bold italic px-3 py-1',
    lcd: 'bg-[#fff5ee] text-[#ff6600] border-2 border-[#ff6600]',
    lcdFont: 'font-sans font-bold',
    button: 'bg-[#ff6600] text-white font-bold rounded-full hover:bg-[#ff8533]',
    panel: 'bg-[#ffffff] border border-[#ff6600]',
    input: 'bg-[#fff5ee] text-[#ff6600] border-2 border-[#ff6600] focus:border-[#ff8533]',
    text: 'text-[#ff6600]',
    highlight: 'bg-[#ff6600] text-white',
    hover: 'hover:bg-[#ffe5cc]'
  },
  msn: {
    name: 'MSN Messenger',
    bg: 'bg-gradient-to-br from-[#4b0082] to-[#8a2be2]',
    window: 'bg-[#f0e6ff] border-2 border-[#9370db] rounded-lg shadow-lg',
    titleBar: 'bg-gradient-to-r from-[#4b0082] to-[#8a2be2] text-white rounded-t-lg font-sans font-bold px-3 py-1',
    lcd: 'bg-[#e6d5f5] text-[#4b0082] border border-[#9370db] rounded-md',
    lcdFont: 'font-sans',
    button: 'bg-gradient-to-b from-[#dda0dd] to-[#ba55d3] text-white border border-[#9370db] rounded-full hover:from-[#ee82ee] hover:to-[#da70d6]',
    panel: 'bg-[#f0e6ff] rounded-md border border-[#dda0dd]',
    input: 'bg-white text-[#4b0082] border border-[#9370db] rounded-full focus:border-[#8a2be2]',
    text: 'text-[#4b0082]',
    highlight: 'bg-[#8a2be2] text-white',
    hover: 'hover:bg-[#e6d5f5]'
  },
  myspace: {
    name: 'MySpace Tom',
    bg: 'bg-[#000000]',
    window: 'bg-[#111111] border-2 border-[#ff0099] shadow-[0_0_10px_#ff0099]',
    titleBar: 'bg-[#ff0099] text-white font-bold uppercase px-2 py-1',
    lcd: 'bg-[#000000] text-[#00ffff] border-2 border-[#ff0099]',
    lcdFont: 'font-mono',
    button: 'bg-[#ff0099] text-white font-bold border-2 border-[#00ffff] hover:bg-[#00ffff] hover:text-black',
    panel: 'bg-[#1a1a1a] border border-[#333333]',
    input: 'bg-[#000000] text-[#00ffff] border-2 border-[#ff0099] focus:border-[#00ffff]',
    text: 'text-[#ff0099]',
    highlight: 'bg-[#00ffff] text-black',
    hover: 'hover:bg-[#222222]'
  },
  limewire: {
    name: 'LimeWire',
    bg: 'bg-[#1a1a1a]',
    window: 'bg-[#2d2d2d] border-2 border-[#32cd32] shadow-[0_0_15px_#32cd32]',
    titleBar: 'bg-[#32cd32] text-black font-bold px-3 py-1',
    lcd: 'bg-[#1a1a1a] text-[#32cd32] border-2 border-[#32cd32]',
    lcdFont: 'font-sans font-bold',
    button: 'bg-[#32cd32] text-black font-bold hover:bg-[#7cfc00]',
    panel: 'bg-[#252525] border border-[#3a3a3a]',
    input: 'bg-[#1a1a1a] text-[#32cd32] border-2 border-[#32cd32] focus:border-[#7cfc00]',
    text: 'text-[#32cd32]',
    highlight: 'bg-[#32cd32] text-black',
    hover: 'hover:bg-[#333333]'
  }
} as const;

export type SkinKey = keyof typeof SKINS;
